//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ContainerStatusHealth.
const (
	ContainerStatusHealthHealthy   ContainerStatusHealth = "healthy"
	ContainerStatusHealthNone      ContainerStatusHealth = "none"
	ContainerStatusHealthStarting  ContainerStatusHealth = "starting"
	ContainerStatusHealthUnhealthy ContainerStatusHealth = "unhealthy"
)

// Defines values for ContainerStatusState.
const (
	ContainerStatusStateCreated    ContainerStatusState = "created"
	ContainerStatusStateDead       ContainerStatusState = "dead"
	ContainerStatusStateExited     ContainerStatusState = "exited"
	ContainerStatusStatePaused     ContainerStatusState = "paused"
	ContainerStatusStateRemoving   ContainerStatusState = "removing"
	ContainerStatusStateRestarting ContainerStatusState = "restarting"
	ContainerStatusStateRunning    ContainerStatusState = "running"
)

// Defines values for DeploymentStatus.
const (
	DeploymentStatusError   DeploymentStatus = "error"
	DeploymentStatusPlanned DeploymentStatus = "planned"
	DeploymentStatusRunning DeploymentStatus = "running"
	DeploymentStatusSuccess DeploymentStatus = "success"
)

// Defines values for EventLevel.
const (
	EventLevelDEBUG EventLevel = "DEBUG"
	EventLevelERROR EventLevel = "ERROR"
	EventLevelINFO  EventLevel = "INFO"
	EventLevelWARN  EventLevel = "WARN"
)

// Defines values for Versions.
const (
	VersionsN10 Versions = "1.0"
)

// AnalyzeResult defines model for AnalyzeResult.
type AnalyzeResult struct {
	Analysis string `json:"analysis"`
	Id       string `json:"id"`
}

// ContainerStatus defines model for ContainerStatus.
type ContainerStatus struct {
	ContainerId string                `json:"containerId"`
	Health      ContainerStatusHealth `json:"health"`
	Name        string                `json:"name"`
	StartedAt   time.Time             `json:"startedAt"`
	State       ContainerStatusState  `json:"state"`
}

// ContainerStatusHealth defines model for ContainerStatus.Health.
type ContainerStatusHealth string

// ContainerStatusState defines model for ContainerStatus.State.
type ContainerStatusState string

// Deployment defines model for Deployment.
type Deployment struct {
	Author string           `json:"author"`
	Diff   string           `json:"diff"`
	Events []Event          `json:"events"`
	Files  []FileDiff       `json:"files"`
	Id     string           `json:"id"`
	Status DeploymentStatus `json:"status"`
	Time   time.Time        `json:"time"`
	Title  string           `json:"title"`
}

// DeploymentStatus defines model for Deployment.Status.
type DeploymentStatus string

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Level EventLevel `json:"level"`
	Msg   string     `json:"msg"`
	Time  time.Time  `json:"time"`
}

// EventLevel defines model for Event.Level.
type EventLevel string

// FileDiff defines model for FileDiff.
type FileDiff struct {
	Diff    string `json:"diff"`
	NewFile string `json:"newFile"`
	OldFile string `json:"oldFile"`
}

// StackStatus defines model for StackStatus.
type StackStatus struct {
	Name     string            `json:"name"`
	Services []ContainerStatus `json:"services"`
	StackId  string            `json:"stackId"`
}

// Versions defines model for Versions.
type Versions string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeployementAPIList request
	DeployementAPIList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeployementAPIRead request
	DeployementAPIRead(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StatusAPIGet request
	StatusAPIGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeployementAPIList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeployementAPIListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeployementAPIRead(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeployementAPIReadRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StatusAPIGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStatusAPIGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeployementAPIListRequest generates requests for DeployementAPIList
func NewDeployementAPIListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/deployment")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeployementAPIReadRequest generates requests for DeployementAPIRead
func NewDeployementAPIReadRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/deployment/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStatusAPIGetRequest generates requests for StatusAPIGet
func NewStatusAPIGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeployementAPIListWithResponse request
	DeployementAPIListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeployementAPIListResponse, error)

	// DeployementAPIReadWithResponse request
	DeployementAPIReadWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeployementAPIReadResponse, error)

	// StatusAPIGetWithResponse request
	StatusAPIGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StatusAPIGetResponse, error)
}

type DeployementAPIListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Deployment
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeployementAPIListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeployementAPIListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeployementAPIReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Deployment
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeployementAPIReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeployementAPIReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StatusAPIGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]StackStatus
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r StatusAPIGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StatusAPIGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeployementAPIListWithResponse request returning *DeployementAPIListResponse
func (c *ClientWithResponses) DeployementAPIListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeployementAPIListResponse, error) {
	rsp, err := c.DeployementAPIList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeployementAPIListResponse(rsp)
}

// DeployementAPIReadWithResponse request returning *DeployementAPIReadResponse
func (c *ClientWithResponses) DeployementAPIReadWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeployementAPIReadResponse, error) {
	rsp, err := c.DeployementAPIRead(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeployementAPIReadResponse(rsp)
}

// StatusAPIGetWithResponse request returning *StatusAPIGetResponse
func (c *ClientWithResponses) StatusAPIGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StatusAPIGetResponse, error) {
	rsp, err := c.StatusAPIGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStatusAPIGetResponse(rsp)
}

// ParseDeployementAPIListResponse parses an HTTP response from a DeployementAPIListWithResponse call
func ParseDeployementAPIListResponse(rsp *http.Response) (*DeployementAPIListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeployementAPIListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeployementAPIReadResponse parses an HTTP response from a DeployementAPIReadWithResponse call
func ParseDeployementAPIReadResponse(rsp *http.Response) (*DeployementAPIReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeployementAPIReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStatusAPIGetResponse parses an HTTP response from a StatusAPIGetWithResponse call
func ParseStatusAPIGetResponse(rsp *http.Response) (*StatusAPIGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StatusAPIGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []StackStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/deployment)
	DeployementAPIList(w http.ResponseWriter, r *http.Request)

	// (GET /api/deployment/{id})
	DeployementAPIRead(w http.ResponseWriter, r *http.Request, id string)

	// (GET /api/status)
	StatusAPIGet(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeployementAPIList operation middleware
func (siw *ServerInterfaceWrapper) DeployementAPIList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployementAPIList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployementAPIRead operation middleware
func (siw *ServerInterfaceWrapper) DeployementAPIRead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployementAPIRead(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StatusAPIGet operation middleware
func (siw *ServerInterfaceWrapper) StatusAPIGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StatusAPIGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/deployment", wrapper.DeployementAPIList)
	m.HandleFunc("GET "+options.BaseURL+"/api/deployment/{id}", wrapper.DeployementAPIRead)
	m.HandleFunc("GET "+options.BaseURL+"/api/status", wrapper.StatusAPIGet)

	return m
}

type DeployementAPIListRequestObject struct {
}

type DeployementAPIListResponseObject interface {
	VisitDeployementAPIListResponse(w http.ResponseWriter) error
}

type DeployementAPIList200JSONResponse []Deployment

func (response DeployementAPIList200JSONResponse) VisitDeployementAPIListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeployementAPIListdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeployementAPIListdefaultJSONResponse) VisitDeployementAPIListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeployementAPIReadRequestObject struct {
	Id string `json:"id"`
}

type DeployementAPIReadResponseObject interface {
	VisitDeployementAPIReadResponse(w http.ResponseWriter) error
}

type DeployementAPIRead200JSONResponse Deployment

func (response DeployementAPIRead200JSONResponse) VisitDeployementAPIReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeployementAPIReaddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeployementAPIReaddefaultJSONResponse) VisitDeployementAPIReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type StatusAPIGetRequestObject struct {
}

type StatusAPIGetResponseObject interface {
	VisitStatusAPIGetResponse(w http.ResponseWriter) error
}

type StatusAPIGet200JSONResponse []StackStatus

func (response StatusAPIGet200JSONResponse) VisitStatusAPIGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StatusAPIGetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StatusAPIGetdefaultJSONResponse) VisitStatusAPIGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/deployment)
	DeployementAPIList(ctx context.Context, request DeployementAPIListRequestObject) (DeployementAPIListResponseObject, error)

	// (GET /api/deployment/{id})
	DeployementAPIRead(ctx context.Context, request DeployementAPIReadRequestObject) (DeployementAPIReadResponseObject, error)

	// (GET /api/status)
	StatusAPIGet(ctx context.Context, request StatusAPIGetRequestObject) (StatusAPIGetResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeployementAPIList operation middleware
func (sh *strictHandler) DeployementAPIList(w http.ResponseWriter, r *http.Request) {
	var request DeployementAPIListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeployementAPIList(ctx, request.(DeployementAPIListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeployementAPIList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeployementAPIListResponseObject); ok {
		if err := validResponse.VisitDeployementAPIListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeployementAPIRead operation middleware
func (sh *strictHandler) DeployementAPIRead(w http.ResponseWriter, r *http.Request, id string) {
	var request DeployementAPIReadRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeployementAPIRead(ctx, request.(DeployementAPIReadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeployementAPIRead")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeployementAPIReadResponseObject); ok {
		if err := validResponse.VisitDeployementAPIReadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StatusAPIGet operation middleware
func (sh *strictHandler) StatusAPIGet(w http.ResponseWriter, r *http.Request) {
	var request StatusAPIGetRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StatusAPIGet(ctx, request.(StatusAPIGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StatusAPIGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StatusAPIGetResponseObject); ok {
		if err := validResponse.VisitStatusAPIGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
