version: 2
updates:

  # Go Backend
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      backend-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        versions: ["*-rc*", "*-alpha*", "*-beta*", "*-pre*"]

  # React Frontend (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*eslint*"
        # Ignore versions 10.x.x and above because of plugin incompatibility, should be remove later
        versions: [">=10.0.0"]
      - dependency-name: "*"
        versions: ["*-rc*", "*-alpha*", "*-beta*", "*-pre*"]

  # Typespec (npm)
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        versions: ["*-rc*", "*-alpha*", "*-beta*", "*-pre*"]

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        versions: ["*-rc*", "*-alpha*", "*-beta*", "*-pre*"]

  # Github actions CI
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        versions: ["*-rc*", "*-alpha*", "*-beta*", "*-pre*"]