package integrationtests

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"omar-kada/autonas/internal/docker"
	"omar-kada/autonas/internal/events"
	"omar-kada/autonas/internal/shell"
	"omar-kada/autonas/testutil"

	"github.com/docker/compose/v2/pkg/api"
	"github.com/stretchr/testify/assert"
	"github.com/testcontainers/testcontainers-go/modules/compose"
)

func TestFileGeneration(t *testing.T) {
	ctx := context.Background()

	// Given
	baseDir, err := os.MkdirTemp("", "flow_test_*")
	assert.NoError(t, err)

	t.Cleanup(func() {
		err = os.RemoveAll(baseDir)
		// print warning in case of errors that may occur in ci
		if err != nil {
			fmt.Printf("WARN : error while cleaning up test files : %v\n", err)
		}
	})

	servicesDir := filepath.Join(baseDir, "services")
	dataDir := filepath.Join(baseDir, "data")
	configDir := filepath.Join(baseDir, "config")
	err = os.Mkdir(servicesDir, 0o750)
	assert.NoError(t, err)
	err = os.Mkdir(dataDir, 0o750)
	assert.NoError(t, err)
	err = os.Mkdir(configDir, 0o750)
	assert.NoError(t, err)

	err = os.WriteFile(filepath.Join(configDir, "config.yaml"),
		[]byte(strings.Join([]string{
			"settings:",
			"  repo: \"https://github.com/omar-kada/autonas-config\"",
			"  cron: \"* * * * *\"",
			"environment:",
			"  AUTONAS_HOST: test",
			"  SERVICES_PATH: " + servicesDir,
			"  DATA_PATH: " + dataDir,
			"services:",
			"  homepage:",
			"    port : 12345",
		}, "\n")), 0o750)
	assert.NoError(t, err, "error while creating config file")

	if _, err := os.Stat("../../.env"); os.IsNotExist(err) {
		err = os.WriteFile("../../.env", []byte{}, 0o750)
		assert.NoError(t, err, "error while creating .env file")
	}

	// When
	// Start docker-compose environment
	composeEnv, err := compose.NewDockerCompose("../../compose.yaml")
	composeEnv.WithEnv(map[string]string{
		"CONFIG_PATH":            filepath.Join(configDir, "config.yaml"),
		"SERVICES_DIR":           servicesDir,
		"AUTONAS_DATA_PATH":      dataDir,
		"AUTONAS_ADD_WRITE_PERM": "true",
		"ENV":                    "DEV",
		"UID":                    fmt.Sprint(os.Getuid()),
		"GID":                    fmt.Sprint(os.Getgid()),
	})

	assert.NoError(t, err, "failed to load compose")

	// Start containers
	if err := composeEnv.Up(ctx, compose.WithRecreate(api.RecreateForce)); err != nil {
		t.Fatalf("failed to start compose: %v", err)
	}
	t.Cleanup(func() {
		if t.Failed() {
			printContainerLogs(ctx, t, composeEnv)
		}
		composeEnv.Down(ctx, compose.RemoveOrphans(true), compose.RemoveVolumes(true))
	})

	// Then
	// Wait for file to be generated (polling)
	targetFile := filepath.Join(servicesDir, "homepage", ".env")

	ok := testutil.WaitForFile(targetFile, 2*time.Minute)
	if !ok {
		t.Fatalf("expected file was not generated: %s", targetFile)
	}
	// Assert env file content
	want := []string{
		"# The next values are generated by AutoNAS :",
		"AUTONAS_HOST=test",
		"DATA_PATH=" + dataDir,
		"SERVICES_PATH=" + servicesDir,
		"PORT=12345",
	}

	content, err := os.ReadFile(targetFile)
	assert.NoError(t, err, "error reading target file")
	for _, val := range want {
		assert.Contains(t, string(content), val, "file should contain correct all env vars")
	}

	targetWorkDir := filepath.Join(servicesDir, "homepage")

	homepageContainers, _ := testutil.WaitForComposeStack(ctx, targetWorkDir, 2*time.Minute)
	assert.NotEmpty(t, homepageContainers, "homepage container not found")

	t.Cleanup(func() {
		/// cleanup homepage container after test finishes
		dockerDeployer := docker.NewDeployer(events.NewVoidDispatcher(), shell.NewExecutor())
		dockerDeployer.RemoveServices([]string{"homepage"}, servicesDir)
	})
}

func printContainerLogs(ctx context.Context, t *testing.T, composeEnv *compose.DockerCompose) {
	t.Helper()

	for _, service := range composeEnv.Services() {

		cont, err := composeEnv.ServiceContainer(ctx, service)
		assert.NoError(t, err)

		logsReader, err := cont.Logs(ctx)
		assert.NoError(t, err)

		bytes, err := io.ReadAll(logsReader)

		assert.NoError(t, err)
		fmt.Printf("Logs for service %s:\n%s\n", service, string(bytes))
	}
}
