package cli

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"omar-kada/air-compose/internal/logs"
	"omar-kada/air-compose/testutil"
	"omar-kada/air-compose/testutil/mocks"

	"github.com/stretchr/testify/assert"
	"gorm.io/gorm"
)

func initConfigRepo(t *testing.T) string {
	remoteRepoPath := testutil.SetupRemoteRepo(t)
	homepageComposeFile, err := os.ReadFile("test_data/homepage/compose.yaml")
	assert.NoError(t, err, "error while reading homepage compose file")
	homepageEnvFile, err := os.ReadFile("test_data/homepage/env")
	assert.NoError(t, err, "error while reading homepage env file")
	testutil.AddCommitToRepo(t, remoteRepoPath, "services/homepage/compose.yaml", homepageComposeFile)
	testutil.AddCommitToRepo(t, remoteRepoPath, "services/homepage/.env", homepageEnvFile)
	if err != nil {
		t.Fatal(err)
	}
	return remoteRepoPath
}

func TestRunCommand_CmdParams(t *testing.T) {
	baseDir := t.TempDir()
	mocker := &mocks.Executor{}
	hub := logs.NewHistoryHub(0)
	cmd := NewRunCommand(mocker, hub, func(_ RunParams) (*gorm.DB, error) {
		return testutil.NewMemoryStorage(t), nil
	})

	servicesDir := filepath.Join(baseDir, "services")
	dataDir := filepath.Join(baseDir, "data")
	workingDir := filepath.Join(baseDir, "work")
	configFile := filepath.Join(workingDir, "config.yaml")
	os.MkdirAll(servicesDir, 0o750)
	os.MkdirAll(dataDir, 0o750)
	os.MkdirAll(workingDir, 0o750)

	mocker.On(
		"Exec", "docker",
		[]string{"compose", "--project-directory", filepath.Join(servicesDir, "homepage"), "--progress", "quiet", "up", "-d", "--quiet-pull"},
	).Return([]byte{}, nil)

	remoteRepoPath := initConfigRepo(t)

	err := os.WriteFile(configFile,
		[]byte(strings.Join([]string{
			"settings:",
			"  git:",
			"    repo: \"" + remoteRepoPath + "\"",
			"  schedule:",
			"    cron : 1",
			"environment:",
			"  SERVICES_PATH: " + servicesDir,
			"  DATA_PATH: " + dataDir,
			"services:",
			"  homepage:",
			"    port : 12345",
		}, "\n")), 0o750)
	assert.NoError(t, err, "error while creating config file")

	t.Setenv("AIR_COMPOSE_CONFIG_FILE", "")
	t.Setenv("AIR_COMPOSE_WORKING_DIR", "")

	go func() {
		cmd.SetArgs([]string{
			"-f", configFile,
			"-d", workingDir,
			"-s", servicesDir,
			"-w", "true",
			"-p", "5008",
		})
		cmd.Execute()
	}()

	targetFile := filepath.Join(servicesDir, "homepage", ".env")

	ok := testutil.WaitForFile(targetFile, 20*time.Second)
	assert.True(t, ok, "homepage files should be created")
}

func TestRunCommand_EnvParams(t *testing.T) {
	baseDir := t.TempDir()
	mocker := &mocks.Executor{}
	hub := logs.NewHistoryHub(0)
	cmd := NewRunCommand(mocker, hub, func(_ RunParams) (*gorm.DB, error) {
		return testutil.NewMemoryStorage(t), nil
	})

	servicesDir := filepath.Join(baseDir, "services")
	dataDir := filepath.Join(baseDir, "data")
	workingDir := filepath.Join(baseDir, "work")
	configFile := filepath.Join(workingDir, "config.yaml")
	os.MkdirAll(servicesDir, 0o750)
	os.MkdirAll(dataDir, 0o750)
	os.MkdirAll(workingDir, 0o750)

	mocker.On(
		"Exec", "docker",
		[]string{"compose", "--project-directory", filepath.Join(servicesDir, "homepage"), "--progress", "quiet", "up", "-d", "--quiet-pull"},
	).Return([]byte{}, nil)

	remoteRepoPath := initConfigRepo(t)

	err := os.WriteFile(configFile,
		[]byte(strings.Join([]string{
			"settings:",
			"  git:",
			"    repo: \"" + remoteRepoPath + "\"",
			"  schedule:",
			"    cron : 1",
			"environment:",
			"  SERVICES_PATH: " + servicesDir,
			"  DATA_PATH: " + dataDir,
			"services:",
			"  homepage:",
			"    port : 12345",
		}, "\n")), 0o750)
	assert.NoError(t, err, "error while creating config file")

	t.Setenv("AIR_COMPOSE_CONFIG_FILE", configFile)
	t.Setenv("AIR_COMPOSE_WORKING_DIR", workingDir)
	t.Setenv("AIR_COMPOSE_SERVICES_DIR", servicesDir)
	t.Setenv("AIR_COMPOSE_ADD_WRITE_PERM", "true")
	t.Setenv("AIR_COMPOSE_PORT", "5009")

	go func() {
		cmd.Execute()
	}()

	targetFile := filepath.Join(servicesDir, "homepage", ".env")

	ok := testutil.WaitForFile(targetFile, 20*time.Second)
	assert.True(t, ok, "homepage files should be created")

	// Assert file content
	want := []string{
		"# The next values are generated by AirCompose :",
		"DATA_PATH=" + dataDir,
		"SERVICES_PATH=" + servicesDir,
		"port=12345",
	}

	content, err := os.ReadFile(targetFile)
	assert.NoError(t, err, "error reading target file")
	for _, val := range want {
		assert.Contains(t, string(content), val, "file should contain correct all env vars")
	}
}

func TestRunCommand_WithInvalidConfig(t *testing.T) {
	mocker := &mocks.Executor{}
	hub := logs.NewHistoryHub(0)
	cmd := NewRunCommand(mocker, hub, func(_ RunParams) (*gorm.DB, error) {
		return nil, errors.New("mock error")
	})

	// Create a channel to capture the command's exit status
	done := make(chan error, 1)

	go func() {
		err := cmd.Execute()
		done <- err
	}()

	select {

	case cmdErr := <-done:
		assert.ErrorContains(t, cmdErr, "mock error")
	case <-time.After(1 * time.Second):
		assert.Fail(t, "timeout while waiting for command error")
	}
}
