package docker

import (
	"fmt"
	"omar-kada/autonas/internal/config"
	"omar-kada/autonas/internal/files"
	"os"
	"path/filepath"
	"strings"

	"github.com/elliotchance/orderedmap/v3"
)

// NewEnvGenerator creates an instance of EnvGenerator
func NewEnvGenerator() *EnvGenerator {
	return &EnvGenerator{
		writer: files.NewWriter(),
	}
}

// EnvGenerator handles generation of .env files for docker compose services
type EnvGenerator struct {
	writer files.Writer
}

func (g EnvGenerator) generateEnvFile(cfg config.Config, servicesDir, service string) error {
	serviceCfg := cfg.PerService(service)
	envFilePath := filepath.Join(servicesDir, service, ".env")

	envMap, err := parseEnvFile(envFilePath)
	if err != nil {
		return err
	}

	var content strings.Builder
	if envMap != nil {
		for key, rawLine := range envMap.AllFromFront() {
			if serviceCfg.Has(key) {
				content.WriteString(fmt.Sprintf("# %s # Overridden by AutoNAS \n", rawLine))
			} else {
				content.WriteString(fmt.Sprintf("%s\n", rawLine))
			}
		}
	}

	content.WriteString("# The next values are generated by AutoNAS : \n")

	for key, value := range serviceCfg.AllFromFront() {
		content.WriteString(fmt.Sprintf("%s=%v\n", key, value))
	}

	return g.writer.WriteToFile(envFilePath, content.String())
}

func parseEnvFile(path string) (*orderedmap.OrderedMap[string, string], error) {
	_, err := os.Stat(path)
	if err != nil {
		return nil, nil // file doesn't exists
	}
	fileContent, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	content := string(fileContent)
	lines := strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n")

	envMap := orderedmap.NewOrderedMap[string, string]()
	for index, rawLine := range lines {
		line := strings.TrimSpace(rawLine)
		splitLine := strings.Split(line, "=")
		if len(splitLine) > 1 {
			envMap.Set(strings.ToUpper(splitLine[0]), rawLine)
		} else {
			envMap.Set(fmt.Sprint(index), rawLine)
		}
	}
	return envMap, nil
}
