/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * AutoNAS API
 * OpenAPI spec version: 1.0
 */
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult
} from '@tanstack/react-query';
import {
    useMutation,
    useQuery
} from '@tanstack/react-query';

import type {
    AxiosError,
    AxiosRequestConfig,
    AxiosResponse
} from 'axios';
import * as axios from 'axios';

export interface BooleanResponse {
  success: boolean;
}

export type ConfigGlobalVariables = {[key: string]: string};

export type ConfigServices = {[key: string]: {[key: string]: string}};

export interface Config {
  globalVariables: ConfigGlobalVariables;
  services: ConfigServices;
}

export type ContainerHealth = typeof ContainerHealth[keyof typeof ContainerHealth];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContainerHealth = {
  healthy: 'healthy',
  unhealthy: 'unhealthy',
  starting: 'starting',
  unknown: 'unknown',
} as const;

export type ContainerStatusState = typeof ContainerStatusState[keyof typeof ContainerStatusState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContainerStatusState = {
  created: 'created',
  running: 'running',
  paused: 'paused',
  restarting: 'restarting',
  removing: 'removing',
  exited: 'exited',
  dead: 'dead',
} as const;

export interface ContainerStatus {
  containerId: string;
  state: ContainerStatusState;
  name: string;
  health: ContainerHealth;
  startedAt: string;
}

export interface Credentials {
  username: string;
  password: string;
}

export interface Deployment {
  id: string;
  title: string;
  author: string;
  time: string;
  endTime: string;
  diff: string;
  status: DeploymentStatus;
}

export type DeploymentStatus = typeof DeploymentStatus[keyof typeof DeploymentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeploymentStatus = {
  planned: 'planned',
  running: 'running',
  success: 'success',
  error: 'error',
} as const;

export interface DeploymentWithDetails {
  id: string;
  title: string;
  author: string;
  time: string;
  endTime: string;
  diff: string;
  status: DeploymentStatus;
  files: FileDiff[];
  events: Event[];
}

export interface Error {
  code: number;
  message: string;
}

export interface Event {
  ID: number;
  time: string;
  msg: string;
  type: EventType;
}

export type EventType = typeof EventType[keyof typeof EventType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventType = {
  MISC: 'MISC',
  ERROR: 'ERROR',
  DEPLOYMENT_STARTED: 'DEPLOYMENT_STARTED',
  DEPLOYMENT_SUCCESS: 'DEPLOYMENT_SUCCESS',
  DEPLOYMENT_ERROR: 'DEPLOYMENT_ERROR',
  CONFIGURATION_UPDATED: 'CONFIGURATION_UPDATED',
  PASSWORD_UPDATED: 'PASSWORD_UPDATED',
  SESSION_REUSED: 'SESSION_REUSED',
} as const;

export interface Features {
  displayConfig: boolean;
  editConfig: boolean;
  displayLogs: boolean;
  editSettings: boolean;
}

export interface FileDiff {
  oldFile: string;
  newFile: string;
  diff: string;
}

export interface PageInfo {
  hasNextPage: boolean;
  endCursor: string;
}

export interface Settings {
  repo: string;
  branch?: string;
  cron?: string;
  username?: string;
  token?: string;
  notificationURL?: string;
  notificationTypes: EventType[];
}

export interface StackStatus {
  stackId: string;
  name: string;
  services: ContainerStatus[];
}

export interface Stats {
  error: number;
  success: number;
  nextDeploy: string;
  lastDeploy: string;
  author: string;
  status: DeploymentStatus;
  health: ContainerHealth;
}

export interface User {
  username: string;
}

export type Versions = typeof Versions[keyof typeof Versions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Versions = {
  '10': '1.0',
} as const;

export type DeployementAPIListParams = {
limit: number;
offset?: string;
};

export type DeployementAPIList200 = {
  items: Deployment[];
  pageInfo: PageInfo;
};

export type RegisterAPIRegistered200 = {
  registered: boolean;
};

export type UserAPIChangePasswordBody = {
  oldPass: string;
  newPass: string;
};

export const configAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Config>> => {
    
    
    return axios.default.get(
      `/api/config`,options
    );
  }




export const getConfigAPIGetQueryKey = () => {
    return [
    `/api/config`
    ] as const;
    }

    
export const getConfigAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConfigAPIGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof configAPIGet>>> = ({ signal }) => configAPIGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConfigAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof configAPIGet>>>
export type ConfigAPIGetQueryError = AxiosError<Error>


export function useConfigAPIGet<TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof configAPIGet>>,
          TError,
          Awaited<ReturnType<typeof configAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConfigAPIGet<TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof configAPIGet>>,
          TError,
          Awaited<ReturnType<typeof configAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConfigAPIGet<TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useConfigAPIGet<TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConfigAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const configAPISet = (
    config: Config, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Config>> => {
    
    
    return axios.default.post(
      `/api/config`,
      config,options
    );
  }



export const getConfigAPISetMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configAPISet>>, TError,{data: Config}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof configAPISet>>, TError,{data: Config}, TContext> => {

const mutationKey = ['configAPISet'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof configAPISet>>, {data: Config}> = (props) => {
          const {data} = props ?? {};

          return  configAPISet(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfigAPISetMutationResult = NonNullable<Awaited<ReturnType<typeof configAPISet>>>
    export type ConfigAPISetMutationBody = Config
    export type ConfigAPISetMutationError = AxiosError<Error>

    export const useConfigAPISet = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configAPISet>>, TError,{data: Config}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof configAPISet>>,
        TError,
        {data: Config},
        TContext
      > => {

      const mutationOptions = getConfigAPISetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * List deployments
 */
export const deployementAPIList = (
    params: DeployementAPIListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeployementAPIList200>> => {
    
    
    return axios.default.get(
      `/api/deployment`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDeployementAPIListQueryKey = (params?: DeployementAPIListParams,) => {
    return [
    `/api/deployment`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDeployementAPIListQueryOptions = <TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(params: DeployementAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeployementAPIListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deployementAPIList>>> = ({ signal }) => deployementAPIList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeployementAPIListQueryResult = NonNullable<Awaited<ReturnType<typeof deployementAPIList>>>
export type DeployementAPIListQueryError = AxiosError<Error>


export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
 params: DeployementAPIListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIList>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
 params: DeployementAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIList>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
 params: DeployementAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
 params: DeployementAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeployementAPIListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Sync and deploy if changes
 */
export const deployementAPISync = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeploymentWithDetails | void>> => {
    
    
    return axios.default.post(
      `/api/deployment`,undefined,options
    );
  }



export const getDeployementAPISyncMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deployementAPISync>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deployementAPISync>>, TError,void, TContext> => {

const mutationKey = ['deployementAPISync'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deployementAPISync>>, void> = () => {
          

          return  deployementAPISync(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeployementAPISyncMutationResult = NonNullable<Awaited<ReturnType<typeof deployementAPISync>>>
    
    export type DeployementAPISyncMutationError = AxiosError<Error>

    export const useDeployementAPISync = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deployementAPISync>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deployementAPISync>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDeployementAPISyncMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Read deployment
 */
export const deployementAPIRead = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeploymentWithDetails>> => {
    
    
    return axios.default.get(
      `/api/deployment/${id}`,options
    );
  }




export const getDeployementAPIReadQueryKey = (id?: string,) => {
    return [
    `/api/deployment/${id}`
    ] as const;
    }

    
export const getDeployementAPIReadQueryOptions = <TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeployementAPIReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deployementAPIRead>>> = ({ signal }) => deployementAPIRead(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeployementAPIReadQueryResult = NonNullable<Awaited<ReturnType<typeof deployementAPIRead>>>
export type DeployementAPIReadQueryError = AxiosError<Error>


export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIRead>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIRead>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIRead>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIRead>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeployementAPIReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const diffAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileDiff[]>> => {
    
    
    return axios.default.get(
      `/api/diff`,options
    );
  }




export const getDiffAPIGetQueryKey = () => {
    return [
    `/api/diff`
    ] as const;
    }

    
export const getDiffAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDiffAPIGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof diffAPIGet>>> = ({ signal }) => diffAPIGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DiffAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof diffAPIGet>>>
export type DiffAPIGetQueryError = AxiosError<Error>


export function useDiffAPIGet<TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof diffAPIGet>>,
          TError,
          Awaited<ReturnType<typeof diffAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDiffAPIGet<TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof diffAPIGet>>,
          TError,
          Awaited<ReturnType<typeof diffAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDiffAPIGet<TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDiffAPIGet<TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDiffAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const featuresAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Features>> => {
    
    
    return axios.default.get(
      `/api/features`,options
    );
  }




export const getFeaturesAPIGetQueryKey = () => {
    return [
    `/api/features`
    ] as const;
    }

    
export const getFeaturesAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFeaturesAPIGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof featuresAPIGet>>> = ({ signal }) => featuresAPIGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FeaturesAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof featuresAPIGet>>>
export type FeaturesAPIGetQueryError = AxiosError<Error>


export function useFeaturesAPIGet<TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof featuresAPIGet>>,
          TError,
          Awaited<ReturnType<typeof featuresAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFeaturesAPIGet<TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof featuresAPIGet>>,
          TError,
          Awaited<ReturnType<typeof featuresAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFeaturesAPIGet<TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFeaturesAPIGet<TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFeaturesAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const authAPILogin = (
    credentials: Credentials, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {
    
    
    return axios.default.post(
      `/api/login`,
      credentials,options
    );
  }



export const getAuthAPILoginMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPILogin>>, TError,{data: Credentials}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authAPILogin>>, TError,{data: Credentials}, TContext> => {

const mutationKey = ['authAPILogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAPILogin>>, {data: Credentials}> = (props) => {
          const {data} = props ?? {};

          return  authAPILogin(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthAPILoginMutationResult = NonNullable<Awaited<ReturnType<typeof authAPILogin>>>
    export type AuthAPILoginMutationBody = Credentials
    export type AuthAPILoginMutationError = AxiosError<Error>

    export const useAuthAPILogin = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPILogin>>, TError,{data: Credentials}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAPILogin>>,
        TError,
        {data: Credentials},
        TContext
      > => {

      const mutationOptions = getAuthAPILoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const logoutAPILogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {
    
    
    return axios.default.post(
      `/api/logout`,undefined,options
    );
  }



export const getLogoutAPILogoutMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutAPILogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logoutAPILogout>>, TError,void, TContext> => {

const mutationKey = ['logoutAPILogout'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutAPILogout>>, void> = () => {
          

          return  logoutAPILogout(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutAPILogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logoutAPILogout>>>
    
    export type LogoutAPILogoutMutationError = AxiosError<Error>

    export const useLogoutAPILogout = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutAPILogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutAPILogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutAPILogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const registerAPIRegistered = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegisterAPIRegistered200>> => {
    
    
    return axios.default.get(
      `/api/register`,options
    );
  }




export const getRegisterAPIRegisteredQueryKey = () => {
    return [
    `/api/register`
    ] as const;
    }

    
export const getRegisterAPIRegisteredQueryOptions = <TData = Awaited<ReturnType<typeof registerAPIRegistered>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerAPIRegistered>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegisterAPIRegisteredQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof registerAPIRegistered>>> = ({ signal }) => registerAPIRegistered({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registerAPIRegistered>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegisterAPIRegisteredQueryResult = NonNullable<Awaited<ReturnType<typeof registerAPIRegistered>>>
export type RegisterAPIRegisteredQueryError = AxiosError<Error>


export function useRegisterAPIRegistered<TData = Awaited<ReturnType<typeof registerAPIRegistered>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerAPIRegistered>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registerAPIRegistered>>,
          TError,
          Awaited<ReturnType<typeof registerAPIRegistered>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegisterAPIRegistered<TData = Awaited<ReturnType<typeof registerAPIRegistered>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerAPIRegistered>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registerAPIRegistered>>,
          TError,
          Awaited<ReturnType<typeof registerAPIRegistered>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegisterAPIRegistered<TData = Awaited<ReturnType<typeof registerAPIRegistered>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerAPIRegistered>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRegisterAPIRegistered<TData = Awaited<ReturnType<typeof registerAPIRegistered>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registerAPIRegistered>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegisterAPIRegisteredQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const registerAPIRegister = (
    credentials: Credentials, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {
    
    
    return axios.default.post(
      `/api/register`,
      credentials,options
    );
  }



export const getRegisterAPIRegisterMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerAPIRegister>>, TError,{data: Credentials}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof registerAPIRegister>>, TError,{data: Credentials}, TContext> => {

const mutationKey = ['registerAPIRegister'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerAPIRegister>>, {data: Credentials}> = (props) => {
          const {data} = props ?? {};

          return  registerAPIRegister(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterAPIRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof registerAPIRegister>>>
    export type RegisterAPIRegisterMutationBody = Credentials
    export type RegisterAPIRegisterMutationError = AxiosError<Error>

    export const useRegisterAPIRegister = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerAPIRegister>>, TError,{data: Credentials}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerAPIRegister>>,
        TError,
        {data: Credentials},
        TContext
      > => {

      const mutationOptions = getRegisterAPIRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const settingsAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Settings>> => {
    
    
    return axios.default.get(
      `/api/settings`,options
    );
  }




export const getSettingsAPIGetQueryKey = () => {
    return [
    `/api/settings`
    ] as const;
    }

    
export const getSettingsAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsAPIGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsAPIGet>>> = ({ signal }) => settingsAPIGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SettingsAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof settingsAPIGet>>>
export type SettingsAPIGetQueryError = AxiosError<Error>


export function useSettingsAPIGet<TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsAPIGet>>,
          TError,
          Awaited<ReturnType<typeof settingsAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsAPIGet<TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsAPIGet>>,
          TError,
          Awaited<ReturnType<typeof settingsAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsAPIGet<TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSettingsAPIGet<TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSettingsAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const settingsAPISet = (
    settings: Settings, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Settings>> => {
    
    
    return axios.default.post(
      `/api/settings`,
      settings,options
    );
  }



export const getSettingsAPISetMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsAPISet>>, TError,{data: Settings}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof settingsAPISet>>, TError,{data: Settings}, TContext> => {

const mutationKey = ['settingsAPISet'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsAPISet>>, {data: Settings}> = (props) => {
          const {data} = props ?? {};

          return  settingsAPISet(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettingsAPISetMutationResult = NonNullable<Awaited<ReturnType<typeof settingsAPISet>>>
    export type SettingsAPISetMutationBody = Settings
    export type SettingsAPISetMutationError = AxiosError<Error>

    export const useSettingsAPISet = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsAPISet>>, TError,{data: Settings}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsAPISet>>,
        TError,
        {data: Settings},
        TContext
      > => {

      const mutationOptions = getSettingsAPISetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const statsAPIGet = (
    days: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Stats>> => {
    
    
    return axios.default.get(
      `/api/stats/${days}`,options
    );
  }




export const getStatsAPIGetQueryKey = (days?: number,) => {
    return [
    `/api/stats/${days}`
    ] as const;
    }

    
export const getStatsAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof statsAPIGet>>, TError = AxiosError<Error>>(days: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatsAPIGetQueryKey(days);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statsAPIGet>>> = ({ signal }) => statsAPIGet(days, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(days), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statsAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StatsAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof statsAPIGet>>>
export type StatsAPIGetQueryError = AxiosError<Error>


export function useStatsAPIGet<TData = Awaited<ReturnType<typeof statsAPIGet>>, TError = AxiosError<Error>>(
 days: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof statsAPIGet>>,
          TError,
          Awaited<ReturnType<typeof statsAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatsAPIGet<TData = Awaited<ReturnType<typeof statsAPIGet>>, TError = AxiosError<Error>>(
 days: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof statsAPIGet>>,
          TError,
          Awaited<ReturnType<typeof statsAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatsAPIGet<TData = Awaited<ReturnType<typeof statsAPIGet>>, TError = AxiosError<Error>>(
 days: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStatsAPIGet<TData = Awaited<ReturnType<typeof statsAPIGet>>, TError = AxiosError<Error>>(
 days: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStatsAPIGetQueryOptions(days,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const statusAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StackStatus[]>> => {
    
    
    return axios.default.get(
      `/api/status`,options
    );
  }




export const getStatusAPIGetQueryKey = () => {
    return [
    `/api/status`
    ] as const;
    }

    
export const getStatusAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatusAPIGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statusAPIGet>>> = ({ signal }) => statusAPIGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StatusAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof statusAPIGet>>>
export type StatusAPIGetQueryError = AxiosError<Error>


export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof statusAPIGet>>,
          TError,
          Awaited<ReturnType<typeof statusAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof statusAPIGet>>,
          TError,
          Awaited<ReturnType<typeof statusAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStatusAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const userAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    
    
    return axios.default.get(
      `/api/user`,options
    );
  }




export const getUserAPIGetQueryKey = () => {
    return [
    `/api/user`
    ] as const;
    }

    
export const getUserAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserAPIGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userAPIGet>>> = ({ signal }) => userAPIGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof userAPIGet>>>
export type UserAPIGetQueryError = AxiosError<Error>


export function useUserAPIGet<TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userAPIGet>>,
          TError,
          Awaited<ReturnType<typeof userAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserAPIGet<TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userAPIGet>>,
          TError,
          Awaited<ReturnType<typeof userAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserAPIGet<TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserAPIGet<TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const userAPIDelete = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {
    
    
    return axios.default.delete(
      `/api/user`,options
    );
  }



export const getUserAPIDeleteMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAPIDelete>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userAPIDelete>>, TError,void, TContext> => {

const mutationKey = ['userAPIDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userAPIDelete>>, void> = () => {
          

          return  userAPIDelete(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserAPIDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof userAPIDelete>>>
    
    export type UserAPIDeleteMutationError = AxiosError<Error>

    export const useUserAPIDelete = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAPIDelete>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userAPIDelete>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUserAPIDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const userAPIChangePassword = (
    userAPIChangePasswordBody: UserAPIChangePasswordBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {
    
    
    return axios.default.post(
      `/api/user/change-password`,
      userAPIChangePasswordBody,options
    );
  }



export const getUserAPIChangePasswordMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAPIChangePassword>>, TError,{data: UserAPIChangePasswordBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userAPIChangePassword>>, TError,{data: UserAPIChangePasswordBody}, TContext> => {

const mutationKey = ['userAPIChangePassword'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userAPIChangePassword>>, {data: UserAPIChangePasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  userAPIChangePassword(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserAPIChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof userAPIChangePassword>>>
    export type UserAPIChangePasswordMutationBody = UserAPIChangePasswordBody
    export type UserAPIChangePasswordMutationError = AxiosError<Error>

    export const useUserAPIChangePassword = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAPIChangePassword>>, TError,{data: UserAPIChangePasswordBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userAPIChangePassword>>,
        TError,
        {data: UserAPIChangePasswordBody},
        TContext
      > => {

      const mutationOptions = getUserAPIChangePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
