/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AutoNAS API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface AnalyzeResult {
  id: string;
  analysis: string;
}

export type ContainerStatusState = typeof ContainerStatusState[keyof typeof ContainerStatusState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContainerStatusState = {
  created: 'created',
  running: 'running',
  paused: 'paused',
  restarting: 'restarting',
  removing: 'removing',
  exited: 'exited',
  dead: 'dead',
} as const;

export type ContainerStatusHealth = typeof ContainerStatusHealth[keyof typeof ContainerStatusHealth];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContainerStatusHealth = {
  healthy: 'healthy',
  unhealthy: 'unhealthy',
  starting: 'starting',
  none: 'none',
} as const;

export interface ContainerStatus {
  containerId: string;
  state: ContainerStatusState;
  name: string;
  health: ContainerStatusHealth;
  startedAt: string;
}

export type DeploymentStatus = typeof DeploymentStatus[keyof typeof DeploymentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeploymentStatus = {
  planned: 'planned',
  running: 'running',
  success: 'success',
  error: 'error',
} as const;

export interface Deployment {
  id: string;
  title: string;
  author: string;
  time: string;
  diff: string;
  files: FileDiff[];
  status: DeploymentStatus;
  events: Event[];
}

export interface Error {
  code: number;
  message: string;
}

export type EventLevel = typeof EventLevel[keyof typeof EventLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventLevel = {
  ERROR: 'ERROR',
  INFO: 'INFO',
  DEBUG: 'DEBUG',
  WARN: 'WARN',
} as const;

export interface Event {
  time: string;
  msg: string;
  level: EventLevel;
}

export interface FileDiff {
  oldFile: string;
  newFile: string;
  diff: string;
}

export interface StackStatus {
  stackId: string;
  name: string;
  services: ContainerStatus[];
}

export type Versions = typeof Versions[keyof typeof Versions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Versions = {
  '10': '1.0',
} as const;

/**
 * List widgets
 */
export const deployementAPIList = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Deployment[]>> => {
    
    
    return axios.default.get(
      `/api/deployment`,options
    );
  }




export const getDeployementAPIListQueryKey = () => {
    return [
    `/api/deployment`
    ] as const;
    }

    
export const getDeployementAPIListQueryOptions = <TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeployementAPIListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deployementAPIList>>> = ({ signal }) => deployementAPIList({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeployementAPIListQueryResult = NonNullable<Awaited<ReturnType<typeof deployementAPIList>>>
export type DeployementAPIListQueryError = AxiosError<Error>


export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIList>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIList>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeployementAPIListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Read widgets
 */
export const deployementAPIRead = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Deployment>> => {
    
    
    return axios.default.get(
      `/api/deployment/${id}`,options
    );
  }




export const getDeployementAPIReadQueryKey = (id?: string,) => {
    return [
    `/api/deployment/${id}`
    ] as const;
    }

    
export const getDeployementAPIReadQueryOptions = <TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeployementAPIReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deployementAPIRead>>> = ({ signal }) => deployementAPIRead(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeployementAPIReadQueryResult = NonNullable<Awaited<ReturnType<typeof deployementAPIRead>>>
export type DeployementAPIReadQueryError = AxiosError<Error>


export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIRead>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIRead>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIRead>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIRead>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeployementAPIReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * List widgets
 */
export const statusAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StackStatus[]>> => {
    
    
    return axios.default.get(
      `/api/status`,options
    );
  }




export const getStatusAPIGetQueryKey = () => {
    return [
    `/api/status`
    ] as const;
    }

    
export const getStatusAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatusAPIGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statusAPIGet>>> = ({ signal }) => statusAPIGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StatusAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof statusAPIGet>>>
export type StatusAPIGetQueryError = AxiosError<Error>


export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof statusAPIGet>>,
          TError,
          Awaited<ReturnType<typeof statusAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof statusAPIGet>>,
          TError,
          Awaited<ReturnType<typeof statusAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStatusAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
