/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AirCompose API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface BooleanResponse {
  success: boolean;
}

export type ClientMessageStartLogsKind = typeof ClientMessageStartLogsKind[keyof typeof ClientMessageStartLogsKind];


export const ClientMessageStartLogsKind = {
  startLogs: 'startLogs',
} as const;

export interface StartLogsMessage {
  previousLines: number;
}

export interface ClientMessageStartLogs {
  kind: ClientMessageStartLogsKind;
  value: StartLogsMessage;
}

export type ClientMessageEndLogsKind = typeof ClientMessageEndLogsKind[keyof typeof ClientMessageEndLogsKind];


export const ClientMessageEndLogsKind = {
  endLogs: 'endLogs',
} as const;

export interface EndLogsMessage { [key: string]: unknown }

export interface ClientMessageEndLogs {
  kind: ClientMessageEndLogsKind;
  value: EndLogsMessage;
}

export type ClientMessage = ClientMessageStartLogs | ClientMessageEndLogs;

export type ConfigGlobalVariables = {[key: string]: string};

export type ConfigServices = {[key: string]: {[key: string]: string}};

export interface Config {
  globalVariables: ConfigGlobalVariables;
  services: ConfigServices;
}

export type ContainerHealth = typeof ContainerHealth[keyof typeof ContainerHealth];


export const ContainerHealth = {
  healthy: 'healthy',
  unhealthy: 'unhealthy',
  starting: 'starting',
  none: 'none',
} as const;

export type ContainerState = typeof ContainerState[keyof typeof ContainerState];


export const ContainerState = {
  created: 'created',
  running: 'running',
  paused: 'paused',
  restarting: 'restarting',
  removing: 'removing',
  exited: 'exited',
  dead: 'dead',
} as const;

export interface ContainerStatus {
  containerId: string;
  state: ContainerState;
  name: string;
  health: ContainerHealth;
  startedAt: string;
}

export interface Credentials {
  username: string;
  password: string;
}

export type DeploymentStatus = typeof DeploymentStatus[keyof typeof DeploymentStatus];


export const DeploymentStatus = {
  planned: 'planned',
  running: 'running',
  success: 'success',
  error: 'error',
} as const;

export interface Deployment {
  id: string;
  title: string;
  author: string;
  time: string;
  endTime: string;
  diff: string;
  status: DeploymentStatus;
}

export interface FileDiff {
  oldFile: string;
  newFile: string;
  diff: string;
}

export type EventType = typeof EventType[keyof typeof EventType];


export const EventType = {
  MISC: 'MISC',
  ERROR: 'ERROR',
  DEPLOYMENT_STARTED: 'DEPLOYMENT_STARTED',
  DEPLOYMENT_SUCCESS: 'DEPLOYMENT_SUCCESS',
  DEPLOYMENT_ERROR: 'DEPLOYMENT_ERROR',
  HEALTH_CHANGE: 'HEALTH_CHANGE',
  CONFIGURATION_UPDATED: 'CONFIGURATION_UPDATED',
  PASSWORD_UPDATED: 'PASSWORD_UPDATED',
  SESSION_REUSED: 'SESSION_REUSED',
} as const;

export interface Event {
  ID: number;
  time: string;
  msg: string;
  type: EventType;
  objectId: number;
  objectName: string;
}

export interface DeploymentWithDetails {
  id: string;
  title: string;
  author: string;
  time: string;
  endTime: string;
  diff: string;
  status: DeploymentStatus;
  files: FileDiff[];
  events: Event[];
  commit: string;
  repo: string;
  branch: string;
}

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export const ErrorCode = {
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REQUEST: 'INVALID_REQUEST',
  NOT_ALLOWED: 'NOT_ALLOWED',
  DISABLED: 'DISABLED',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
} as const;

export interface Error {
  code: ErrorCode;
  message: string;
}

export interface EventMessage {
  type: EventType;
  msg: string;
  deploymentId?: number;
  isNotification: boolean;
}

export interface Features {
  displayConfig: boolean;
  editConfig: boolean;
  displayLogs: boolean;
  editSettings: boolean;
}

export interface GitCredentials {
  repo: string;
  branch?: string;
  username?: string;
  token?: string;
}

export type Level = typeof Level[keyof typeof Level];


export const Level = {
  ERROR: 'ERROR',
  WARN: 'WARN',
  INFO: 'INFO',
  DEBUG: 'DEBUG',
} as const;

export interface LogLine {
  msg: string;
  time: string;
  level: Level;
}

export type LogMessages = LogLine[];

export interface OidcSettings {
  issuerURL: string;
  clientID: string;
  clientSecret: string;
}

export interface PageInfo {
  hasNextPage: boolean;
  endCursor: string;
}

export interface RegistrationInfo {
  registered: boolean;
  oidc: boolean;
}

export type ServerMessageLogKind = typeof ServerMessageLogKind[keyof typeof ServerMessageLogKind];


export const ServerMessageLogKind = {
  log: 'log',
} as const;

export interface ServerMessageLog {
  kind: ServerMessageLogKind;
  value: LogLine;
}

export type ServerMessagePreviousLogsKind = typeof ServerMessagePreviousLogsKind[keyof typeof ServerMessagePreviousLogsKind];


export const ServerMessagePreviousLogsKind = {
  previousLogs: 'previousLogs',
} as const;

export interface ServerMessagePreviousLogs {
  kind: ServerMessagePreviousLogsKind;
  value: LogMessages;
}

export type ServerMessageNewDeploymentKind = typeof ServerMessageNewDeploymentKind[keyof typeof ServerMessageNewDeploymentKind];


export const ServerMessageNewDeploymentKind = {
  newDeployment: 'newDeployment',
} as const;

export interface ServerMessageNewDeployment {
  kind: ServerMessageNewDeploymentKind;
  value: Deployment;
}

export type ServerMessageEventKind = typeof ServerMessageEventKind[keyof typeof ServerMessageEventKind];


export const ServerMessageEventKind = {
  event: 'event',
} as const;

export interface ServerMessageEvent {
  kind: ServerMessageEventKind;
  value: EventMessage;
}

export type ServerMessageErrorKind = typeof ServerMessageErrorKind[keyof typeof ServerMessageErrorKind];


export const ServerMessageErrorKind = {
  error: 'error',
} as const;

export interface ServerMessageError {
  kind: ServerMessageErrorKind;
  value: Error;
}

export type ServerMessage = ServerMessageLog | ServerMessagePreviousLogs | ServerMessageNewDeployment | ServerMessageEvent | ServerMessageError;

export interface Settings {
  repo: string;
  branch?: string;
  cron?: string;
  username?: string;
  token?: string;
  notificationURL?: string;
  notificationTypes: EventType[];
  oidc?: OidcSettings;
  retriesOnUnhealthy: number;
  retryDelay: number;
}

export interface StackStatus {[key: string]: {[key: string]: ContainerStatus}}

export interface State {
  nextDeploy: string;
  status: DeploymentStatus;
  health: ContainerHealth;
  initialized: boolean;
}

export type UserType = typeof UserType[keyof typeof UserType];


export const UserType = {
  LOCAL: 'LOCAL',
  OIDC: 'OIDC',
} as const;

export interface User {
  username: string;
  type: UserType;
}

export type Versions = typeof Versions[keyof typeof Versions];


export const Versions = {
  '10': '1.0',
} as const;

export type DeployementAPIListParams = {
limit: number;
offset?: string;
};

export type DeployementAPIList200 = {
  items: Deployment[];
  pageInfo: PageInfo;
};

export type NotificationsAPIListParams = {
limit: number;
offset?: string;
};

export type NotificationsAPIList200 = {
  items: Event[];
  pageInfo: PageInfo;
};

export type OIDCAPIOidcCallbackParams = {
code: string;
state: string;
};

export type UserAPIChangePasswordBody = {
  oldPass: string;
  newPass: string;
};

export const authAPILogin = (
    credentials: Credentials, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {


    return axios.default.post(
      `/api/auth/login`,
      credentials,options
    );
  }



export const getAuthAPILoginMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPILogin>>, TError,{data: Credentials}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authAPILogin>>, TError,{data: Credentials}, TContext> => {

const mutationKey = ['authAPILogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAPILogin>>, {data: Credentials}> = (props) => {
          const {data} = props ?? {};

          return  authAPILogin(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAPILoginMutationResult = NonNullable<Awaited<ReturnType<typeof authAPILogin>>>
    export type AuthAPILoginMutationBody = Credentials
    export type AuthAPILoginMutationError = AxiosError<Error>

    export const useAuthAPILogin = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPILogin>>, TError,{data: Credentials}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAPILogin>>,
        TError,
        {data: Credentials},
        TContext
      > => {
      return useMutation(getAuthAPILoginMutationOptions(options), queryClient);
    }

export const authAPILogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {


    return axios.default.post(
      `/api/auth/logout`,undefined,options
    );
  }



export const getAuthAPILogoutMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPILogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authAPILogout>>, TError,void, TContext> => {

const mutationKey = ['authAPILogout'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAPILogout>>, void> = () => {


          return  authAPILogout(axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAPILogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authAPILogout>>>

    export type AuthAPILogoutMutationError = AxiosError<Error>

    export const useAuthAPILogout = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPILogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAPILogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthAPILogoutMutationOptions(options), queryClient);
    }

export const authAPIRefresh = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {


    return axios.default.post(
      `/api/auth/refresh`,undefined,options
    );
  }



export const getAuthAPIRefreshMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPIRefresh>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authAPIRefresh>>, TError,void, TContext> => {

const mutationKey = ['authAPIRefresh'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAPIRefresh>>, void> = () => {


          return  authAPIRefresh(axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAPIRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authAPIRefresh>>>

    export type AuthAPIRefreshMutationError = AxiosError<Error>

    export const useAuthAPIRefresh = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPIRefresh>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAPIRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthAPIRefreshMutationOptions(options), queryClient);
    }

export const authAPIRegistered = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegistrationInfo>> => {


    return axios.default.get(
      `/api/auth/register`,options
    );
  }




export const getAuthAPIRegisteredQueryKey = () => {
    return [
    `/api/auth/register`
    ] as const;
    }


export const getAuthAPIRegisteredQueryOptions = <TData = Awaited<ReturnType<typeof authAPIRegistered>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAPIRegistered>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthAPIRegisteredQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authAPIRegistered>>> = ({ signal }) => authAPIRegistered({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authAPIRegistered>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthAPIRegisteredQueryResult = NonNullable<Awaited<ReturnType<typeof authAPIRegistered>>>
export type AuthAPIRegisteredQueryError = AxiosError<Error>


export function useAuthAPIRegistered<TData = Awaited<ReturnType<typeof authAPIRegistered>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAPIRegistered>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authAPIRegistered>>,
          TError,
          Awaited<ReturnType<typeof authAPIRegistered>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthAPIRegistered<TData = Awaited<ReturnType<typeof authAPIRegistered>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAPIRegistered>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authAPIRegistered>>,
          TError,
          Awaited<ReturnType<typeof authAPIRegistered>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthAPIRegistered<TData = Awaited<ReturnType<typeof authAPIRegistered>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAPIRegistered>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthAPIRegistered<TData = Awaited<ReturnType<typeof authAPIRegistered>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAPIRegistered>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthAPIRegisteredQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const authAPIRegister = (
    credentials: Credentials, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {


    return axios.default.post(
      `/api/auth/register`,
      credentials,options
    );
  }



export const getAuthAPIRegisterMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPIRegister>>, TError,{data: Credentials}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authAPIRegister>>, TError,{data: Credentials}, TContext> => {

const mutationKey = ['authAPIRegister'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authAPIRegister>>, {data: Credentials}> = (props) => {
          const {data} = props ?? {};

          return  authAPIRegister(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthAPIRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authAPIRegister>>>
    export type AuthAPIRegisterMutationBody = Credentials
    export type AuthAPIRegisterMutationError = AxiosError<Error>

    export const useAuthAPIRegister = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authAPIRegister>>, TError,{data: Credentials}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authAPIRegister>>,
        TError,
        {data: Credentials},
        TContext
      > => {
      return useMutation(getAuthAPIRegisterMutationOptions(options), queryClient);
    }

export const configAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Config>> => {


    return axios.default.get(
      `/api/config`,options
    );
  }




export const getConfigAPIGetQueryKey = () => {
    return [
    `/api/config`
    ] as const;
    }


export const getConfigAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConfigAPIGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof configAPIGet>>> = ({ signal }) => configAPIGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConfigAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof configAPIGet>>>
export type ConfigAPIGetQueryError = AxiosError<Error>


export function useConfigAPIGet<TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof configAPIGet>>,
          TError,
          Awaited<ReturnType<typeof configAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConfigAPIGet<TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof configAPIGet>>,
          TError,
          Awaited<ReturnType<typeof configAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConfigAPIGet<TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useConfigAPIGet<TData = Awaited<ReturnType<typeof configAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof configAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConfigAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const configAPISet = (
    config: Config, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Config>> => {


    return axios.default.post(
      `/api/config`,
      config,options
    );
  }



export const getConfigAPISetMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configAPISet>>, TError,{data: Config}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof configAPISet>>, TError,{data: Config}, TContext> => {

const mutationKey = ['configAPISet'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof configAPISet>>, {data: Config}> = (props) => {
          const {data} = props ?? {};

          return  configAPISet(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConfigAPISetMutationResult = NonNullable<Awaited<ReturnType<typeof configAPISet>>>
    export type ConfigAPISetMutationBody = Config
    export type ConfigAPISetMutationError = AxiosError<Error>

    export const useConfigAPISet = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configAPISet>>, TError,{data: Config}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof configAPISet>>,
        TError,
        {data: Config},
        TContext
      > => {
      return useMutation(getConfigAPISetMutationOptions(options), queryClient);
    }

/**
 * List deployments
 */
export const deployementAPIList = (
    params: DeployementAPIListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeployementAPIList200>> => {


    return axios.default.get(
      `/api/deployment`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDeployementAPIListQueryKey = (params?: DeployementAPIListParams,) => {
    return [
    `/api/deployment`, ...(params ? [params] : [])
    ] as const;
    }


export const getDeployementAPIListQueryOptions = <TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(params: DeployementAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeployementAPIListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deployementAPIList>>> = ({ signal }) => deployementAPIList(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeployementAPIListQueryResult = NonNullable<Awaited<ReturnType<typeof deployementAPIList>>>
export type DeployementAPIListQueryError = AxiosError<Error>


export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
 params: DeployementAPIListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIList>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
 params: DeployementAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIList>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
 params: DeployementAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeployementAPIList<TData = Awaited<ReturnType<typeof deployementAPIList>>, TError = AxiosError<Error>>(
 params: DeployementAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeployementAPIListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Sync and deploy if changes
 */
export const deployementAPISync = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeploymentWithDetails | void>> => {


    return axios.default.post(
      `/api/deployment`,undefined,options
    );
  }



export const getDeployementAPISyncMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deployementAPISync>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deployementAPISync>>, TError,void, TContext> => {

const mutationKey = ['deployementAPISync'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deployementAPISync>>, void> = () => {


          return  deployementAPISync(axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeployementAPISyncMutationResult = NonNullable<Awaited<ReturnType<typeof deployementAPISync>>>

    export type DeployementAPISyncMutationError = AxiosError<Error>

    export const useDeployementAPISync = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deployementAPISync>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deployementAPISync>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeployementAPISyncMutationOptions(options), queryClient);
    }

/**
 * Read deployment
 */
export const deployementAPIRead = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeploymentWithDetails>> => {


    return axios.default.get(
      `/api/deployment/${id}`,options
    );
  }




export const getDeployementAPIReadQueryKey = (id: string,) => {
    return [
    `/api/deployment/${id}`
    ] as const;
    }


export const getDeployementAPIReadQueryOptions = <TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeployementAPIReadQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deployementAPIRead>>> = ({ signal }) => deployementAPIRead(id, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeployementAPIReadQueryResult = NonNullable<Awaited<ReturnType<typeof deployementAPIRead>>>
export type DeployementAPIReadQueryError = AxiosError<Error>


export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIRead>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIRead>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deployementAPIRead>>,
          TError,
          Awaited<ReturnType<typeof deployementAPIRead>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeployementAPIRead<TData = Awaited<ReturnType<typeof deployementAPIRead>>, TError = AxiosError<Error>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deployementAPIRead>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeployementAPIReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const diffAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileDiff[]>> => {


    return axios.default.get(
      `/api/diff`,options
    );
  }




export const getDiffAPIGetQueryKey = () => {
    return [
    `/api/diff`
    ] as const;
    }


export const getDiffAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDiffAPIGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof diffAPIGet>>> = ({ signal }) => diffAPIGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DiffAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof diffAPIGet>>>
export type DiffAPIGetQueryError = AxiosError<Error>


export function useDiffAPIGet<TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof diffAPIGet>>,
          TError,
          Awaited<ReturnType<typeof diffAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDiffAPIGet<TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof diffAPIGet>>,
          TError,
          Awaited<ReturnType<typeof diffAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDiffAPIGet<TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDiffAPIGet<TData = Awaited<ReturnType<typeof diffAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diffAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDiffAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const featuresAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Features>> => {


    return axios.default.get(
      `/api/features`,options
    );
  }




export const getFeaturesAPIGetQueryKey = () => {
    return [
    `/api/features`
    ] as const;
    }


export const getFeaturesAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFeaturesAPIGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof featuresAPIGet>>> = ({ signal }) => featuresAPIGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FeaturesAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof featuresAPIGet>>>
export type FeaturesAPIGetQueryError = AxiosError<Error>


export function useFeaturesAPIGet<TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof featuresAPIGet>>,
          TError,
          Awaited<ReturnType<typeof featuresAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFeaturesAPIGet<TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof featuresAPIGet>>,
          TError,
          Awaited<ReturnType<typeof featuresAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFeaturesAPIGet<TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFeaturesAPIGet<TData = Awaited<ReturnType<typeof featuresAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof featuresAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFeaturesAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const notificationsAPIList = (
    params: NotificationsAPIListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NotificationsAPIList200>> => {


    return axios.default.get(
      `/api/notifications`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getNotificationsAPIListQueryKey = (params?: NotificationsAPIListParams,) => {
    return [
    `/api/notifications`, ...(params ? [params] : [])
    ] as const;
    }


export const getNotificationsAPIListQueryOptions = <TData = Awaited<ReturnType<typeof notificationsAPIList>>, TError = AxiosError<Error>>(params: NotificationsAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsAPIListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsAPIList>>> = ({ signal }) => notificationsAPIList(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationsAPIList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsAPIListQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsAPIList>>>
export type NotificationsAPIListQueryError = AxiosError<Error>


export function useNotificationsAPIList<TData = Awaited<ReturnType<typeof notificationsAPIList>>, TError = AxiosError<Error>>(
 params: NotificationsAPIListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsAPIList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsAPIList>>,
          TError,
          Awaited<ReturnType<typeof notificationsAPIList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsAPIList<TData = Awaited<ReturnType<typeof notificationsAPIList>>, TError = AxiosError<Error>>(
 params: NotificationsAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsAPIList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsAPIList>>,
          TError,
          Awaited<ReturnType<typeof notificationsAPIList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsAPIList<TData = Awaited<ReturnType<typeof notificationsAPIList>>, TError = AxiosError<Error>>(
 params: NotificationsAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationsAPIList<TData = Awaited<ReturnType<typeof notificationsAPIList>>, TError = AxiosError<Error>>(
 params: NotificationsAPIListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsAPIList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationsAPIListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const oIDCAPIOidcCallback = (
    params: OIDCAPIOidcCallbackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.get(
      `/api/oidc/callback`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getOIDCAPIOidcCallbackQueryKey = (params?: OIDCAPIOidcCallbackParams,) => {
    return [
    `/api/oidc/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const getOIDCAPIOidcCallbackQueryOptions = <TData = Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError = AxiosError<Error>>(params: OIDCAPIOidcCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOIDCAPIOidcCallbackQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof oIDCAPIOidcCallback>>> = ({ signal }) => oIDCAPIOidcCallback(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OIDCAPIOidcCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof oIDCAPIOidcCallback>>>
export type OIDCAPIOidcCallbackQueryError = AxiosError<Error>


export function useOIDCAPIOidcCallback<TData = Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError = AxiosError<Error>>(
 params: OIDCAPIOidcCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof oIDCAPIOidcCallback>>,
          TError,
          Awaited<ReturnType<typeof oIDCAPIOidcCallback>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOIDCAPIOidcCallback<TData = Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError = AxiosError<Error>>(
 params: OIDCAPIOidcCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof oIDCAPIOidcCallback>>,
          TError,
          Awaited<ReturnType<typeof oIDCAPIOidcCallback>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOIDCAPIOidcCallback<TData = Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError = AxiosError<Error>>(
 params: OIDCAPIOidcCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOIDCAPIOidcCallback<TData = Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError = AxiosError<Error>>(
 params: OIDCAPIOidcCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcCallback>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOIDCAPIOidcCallbackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const oIDCAPIOidcLogin = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.get(
      `/api/oidc/login`,options
    );
  }




export const getOIDCAPIOidcLoginQueryKey = () => {
    return [
    `/api/oidc/login`
    ] as const;
    }


export const getOIDCAPIOidcLoginQueryOptions = <TData = Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOIDCAPIOidcLoginQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof oIDCAPIOidcLogin>>> = ({ signal }) => oIDCAPIOidcLogin({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OIDCAPIOidcLoginQueryResult = NonNullable<Awaited<ReturnType<typeof oIDCAPIOidcLogin>>>
export type OIDCAPIOidcLoginQueryError = AxiosError<Error>


export function useOIDCAPIOidcLogin<TData = Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof oIDCAPIOidcLogin>>,
          TError,
          Awaited<ReturnType<typeof oIDCAPIOidcLogin>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOIDCAPIOidcLogin<TData = Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof oIDCAPIOidcLogin>>,
          TError,
          Awaited<ReturnType<typeof oIDCAPIOidcLogin>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOIDCAPIOidcLogin<TData = Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOIDCAPIOidcLogin<TData = Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oIDCAPIOidcLogin>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOIDCAPIOidcLoginQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const settingsAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Settings>> => {


    return axios.default.get(
      `/api/settings`,options
    );
  }




export const getSettingsAPIGetQueryKey = () => {
    return [
    `/api/settings`
    ] as const;
    }


export const getSettingsAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsAPIGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsAPIGet>>> = ({ signal }) => settingsAPIGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SettingsAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof settingsAPIGet>>>
export type SettingsAPIGetQueryError = AxiosError<Error>


export function useSettingsAPIGet<TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsAPIGet>>,
          TError,
          Awaited<ReturnType<typeof settingsAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsAPIGet<TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsAPIGet>>,
          TError,
          Awaited<ReturnType<typeof settingsAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsAPIGet<TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSettingsAPIGet<TData = Awaited<ReturnType<typeof settingsAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSettingsAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const settingsAPISet = (
    settings: Settings, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Settings>> => {


    return axios.default.post(
      `/api/settings`,
      settings,options
    );
  }



export const getSettingsAPISetMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsAPISet>>, TError,{data: Settings}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof settingsAPISet>>, TError,{data: Settings}, TContext> => {

const mutationKey = ['settingsAPISet'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsAPISet>>, {data: Settings}> = (props) => {
          const {data} = props ?? {};

          return  settingsAPISet(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsAPISetMutationResult = NonNullable<Awaited<ReturnType<typeof settingsAPISet>>>
    export type SettingsAPISetMutationBody = Settings
    export type SettingsAPISetMutationError = AxiosError<Error>

    export const useSettingsAPISet = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsAPISet>>, TError,{data: Settings}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsAPISet>>,
        TError,
        {data: Settings},
        TContext
      > => {
      return useMutation(getSettingsAPISetMutationOptions(options), queryClient);
    }

export const settingsAPITestGitConnection = (
    gitCredentials: GitCredentials, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {


    return axios.default.post(
      `/api/settings/test-git`,
      gitCredentials,options
    );
  }



export const getSettingsAPITestGitConnectionMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsAPITestGitConnection>>, TError,{data: GitCredentials}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof settingsAPITestGitConnection>>, TError,{data: GitCredentials}, TContext> => {

const mutationKey = ['settingsAPITestGitConnection'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsAPITestGitConnection>>, {data: GitCredentials}> = (props) => {
          const {data} = props ?? {};

          return  settingsAPITestGitConnection(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SettingsAPITestGitConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof settingsAPITestGitConnection>>>
    export type SettingsAPITestGitConnectionMutationBody = GitCredentials
    export type SettingsAPITestGitConnectionMutationError = AxiosError<Error>

    export const useSettingsAPITestGitConnection = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsAPITestGitConnection>>, TError,{data: GitCredentials}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settingsAPITestGitConnection>>,
        TError,
        {data: GitCredentials},
        TContext
      > => {
      return useMutation(getSettingsAPITestGitConnectionMutationOptions(options), queryClient);
    }

export const stateAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<State>> => {


    return axios.default.get(
      `/api/state`,options
    );
  }




export const getStateAPIGetQueryKey = () => {
    return [
    `/api/state`
    ] as const;
    }


export const getStateAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof stateAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stateAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStateAPIGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof stateAPIGet>>> = ({ signal }) => stateAPIGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof stateAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StateAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof stateAPIGet>>>
export type StateAPIGetQueryError = AxiosError<Error>


export function useStateAPIGet<TData = Awaited<ReturnType<typeof stateAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof stateAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof stateAPIGet>>,
          TError,
          Awaited<ReturnType<typeof stateAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStateAPIGet<TData = Awaited<ReturnType<typeof stateAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stateAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof stateAPIGet>>,
          TError,
          Awaited<ReturnType<typeof stateAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStateAPIGet<TData = Awaited<ReturnType<typeof stateAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stateAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStateAPIGet<TData = Awaited<ReturnType<typeof stateAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stateAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStateAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const statusAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StackStatus>> => {


    return axios.default.get(
      `/api/status`,options
    );
  }




export const getStatusAPIGetQueryKey = () => {
    return [
    `/api/status`
    ] as const;
    }


export const getStatusAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatusAPIGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof statusAPIGet>>> = ({ signal }) => statusAPIGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StatusAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof statusAPIGet>>>
export type StatusAPIGetQueryError = AxiosError<Error>


export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof statusAPIGet>>,
          TError,
          Awaited<ReturnType<typeof statusAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof statusAPIGet>>,
          TError,
          Awaited<ReturnType<typeof statusAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStatusAPIGet<TData = Awaited<ReturnType<typeof statusAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statusAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStatusAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const userAPIGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {


    return axios.default.get(
      `/api/user`,options
    );
  }




export const getUserAPIGetQueryKey = () => {
    return [
    `/api/user`
    ] as const;
    }


export const getUserAPIGetQueryOptions = <TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserAPIGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof userAPIGet>>> = ({ signal }) => userAPIGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserAPIGetQueryResult = NonNullable<Awaited<ReturnType<typeof userAPIGet>>>
export type UserAPIGetQueryError = AxiosError<Error>


export function useUserAPIGet<TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userAPIGet>>,
          TError,
          Awaited<ReturnType<typeof userAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserAPIGet<TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userAPIGet>>,
          TError,
          Awaited<ReturnType<typeof userAPIGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserAPIGet<TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserAPIGet<TData = Awaited<ReturnType<typeof userAPIGet>>, TError = AxiosError<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAPIGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserAPIGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const userAPIDelete = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {


    return axios.default.delete(
      `/api/user`,options
    );
  }



export const getUserAPIDeleteMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAPIDelete>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userAPIDelete>>, TError,void, TContext> => {

const mutationKey = ['userAPIDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userAPIDelete>>, void> = () => {


          return  userAPIDelete(axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserAPIDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof userAPIDelete>>>

    export type UserAPIDeleteMutationError = AxiosError<Error>

    export const useUserAPIDelete = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAPIDelete>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userAPIDelete>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUserAPIDeleteMutationOptions(options), queryClient);
    }

export const userAPIChangePassword = (
    userAPIChangePasswordBody: UserAPIChangePasswordBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BooleanResponse>> => {


    return axios.default.post(
      `/api/user/change-password`,
      userAPIChangePasswordBody,options
    );
  }



export const getUserAPIChangePasswordMutationOptions = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAPIChangePassword>>, TError,{data: UserAPIChangePasswordBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userAPIChangePassword>>, TError,{data: UserAPIChangePasswordBody}, TContext> => {

const mutationKey = ['userAPIChangePassword'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userAPIChangePassword>>, {data: UserAPIChangePasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  userAPIChangePassword(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UserAPIChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof userAPIChangePassword>>>
    export type UserAPIChangePasswordMutationBody = UserAPIChangePasswordBody
    export type UserAPIChangePasswordMutationError = AxiosError<Error>

    export const useUserAPIChangePassword = <TError = AxiosError<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userAPIChangePassword>>, TError,{data: UserAPIChangePasswordBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userAPIChangePassword>>,
        TError,
        {data: UserAPIChangePasswordBody},
        TContext
      > => {
      return useMutation(getUserAPIChangePasswordMutationOptions(options), queryClient);
    }

export const webSocketConnect = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {


    return axios.default.get(
      `/api/ws`,options
    );
  }




export const getWebSocketConnectQueryKey = () => {
    return [
    `/api/ws`
    ] as const;
    }


export const getWebSocketConnectQueryOptions = <TData = Awaited<ReturnType<typeof webSocketConnect>>, TError = AxiosError<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webSocketConnect>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebSocketConnectQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof webSocketConnect>>> = ({ signal }) => webSocketConnect({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof webSocketConnect>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WebSocketConnectQueryResult = NonNullable<Awaited<ReturnType<typeof webSocketConnect>>>
export type WebSocketConnectQueryError = AxiosError<void>


export function useWebSocketConnect<TData = Awaited<ReturnType<typeof webSocketConnect>>, TError = AxiosError<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof webSocketConnect>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof webSocketConnect>>,
          TError,
          Awaited<ReturnType<typeof webSocketConnect>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebSocketConnect<TData = Awaited<ReturnType<typeof webSocketConnect>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webSocketConnect>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof webSocketConnect>>,
          TError,
          Awaited<ReturnType<typeof webSocketConnect>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebSocketConnect<TData = Awaited<ReturnType<typeof webSocketConnect>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webSocketConnect>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWebSocketConnect<TData = Awaited<ReturnType<typeof webSocketConnect>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webSocketConnect>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWebSocketConnectQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
