package docker

import (
	"errors"
	"fmt"
	"omar-kada/autonas/internal/config"
	"omar-kada/autonas/internal/files"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

type Mocker struct {
	mock.Mock
}

func (m *Mocker) WriteToFile(filePath string, content string) error {
	args := m.Called(filePath, content)
	return args.Error(0)
}

func (m *Mocker) Run(cmd string, cmdArgs ...string) error {
	args := m.Called(cmd, cmdArgs)
	return args.Error(0)
}

func newManagerWithMocks(mocker *Mocker) *Deployer {
	return &Deployer{
		writer:    mocker,
		cmdRunner: mocker,
	}
}

var mockConfig = config.Config{
	Extra: map[string]any{
		"AUTONAS_HOST": "localhost",
	},
	Services: map[string]config.ServiceConfig{
		"svc1": {
			Extra: map[string]any{
				"Port": "8080",
			},
		},
		"svc2": {
			Disabled: true,
			Extra: map[string]any{
				"Version": "v2",
			},
		},
	},
}

func TestDeployServices_SingleService_WithOverride(t *testing.T) {
	mocker := &Mocker{}
	manager := newManagerWithMocks(mocker)

	baseDir := t.TempDir()
	envFilePath := filepath.Join(baseDir, "svc1", ".env")
	err := os.Mkdir(filepath.Join(baseDir, "svc1"), 0750)
	assert.NoError(t, err)

	err = files.NewWriter().WriteToFile(
		envFilePath,
		"CUSTOM_VAR=will not be overridden\n\n"+
			"PORT=80",
	)

	assert.NoError(t, err)

	wantEnv := strings.Join([]string{
		"CUSTOM_VAR=will not be overridden",
		"",
		"# PORT=80 # Overridden by AutoNAS ",
		"# The next values are generated by AutoNAS : ",
		"AUTONAS_HOST=localhost",
		"PORT=8080",
	}, "\n") + "\n"
	mock.InOrder(
		mocker.On("WriteToFile", envFilePath, wantEnv).Return(nil),
		mocker.On(
			"Run", "docker", []string{"compose", "--project-directory", filepath.Join(baseDir, "svc1"), "up", "-d"},
		).Return(nil),
	)
	err = manager.DeployServices(mockConfig, baseDir)
	assert.NoError(t, err)
}

func TestRemoveServices_MultipleServices(t *testing.T) {
	mocker := &Mocker{}
	baseDir := t.TempDir()

	manager := newManagerWithMocks(mocker)
	mocker.On(
		"Run", "docker", []string{"compose", "--project-directory", filepath.Join(baseDir, "svc1"), "down"},
	).Return(nil)
	mocker.On(
		"Run", "docker", []string{"compose", "--project-directory", filepath.Join(baseDir, "svc2"), "down"},
	).Return(fmt.Errorf("mock error"))
	err := manager.RemoveServices([]string{"svc1", "svc2"}, baseDir)

	assert.NoError(t, err)
}

type ExpectedErrors struct {
	writeFileErr error
	runCmdErr    error
}

var (
	ErrWriteFile = errors.New("writeFile error")
	ErrRunCmd    = errors.New("runCmd error")
)

func TestDeployServices_Errors(t *testing.T) {
	t.Skip("temporarily disabled until deploy returns proper errors")
	testCases := []struct {
		name          string
		errors        ExpectedErrors
		expectedError error
	}{
		{
			name:          "writeFile error",
			errors:        ExpectedErrors{writeFileErr: ErrWriteFile},
			expectedError: ErrWriteFile,
		},
		{
			name:          "runCmd error",
			errors:        ExpectedErrors{runCmdErr: ErrRunCmd},
			expectedError: ErrRunCmd,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			mocker := &Mocker{}
			manager := newManagerWithMocks(mocker)
			mocker.On("WriteToFile", mock.Anything, mock.Anything).Return(tc.errors.writeFileErr)
			mocker.On("Run", "docker", mock.Anything).Return(tc.errors.runCmdErr)
			err := manager.DeployServices(mockConfig, "/services")
			// TODO : add tests for aggregared errors
			assert.ErrorIs(t, err, tc.expectedError)
		})
	}
}
