AUTONAS_HOST: host
DATA_PATH: /data
SERVICES_PATH: /services
services:
  svc:
    PORT: 2000
    VERSION: v2
    NEW_FIELD: new_value
  svc2:
    PORT: 1234
    VERSION: v1
    OTHER_FIELD: other_value