- Services:
    - Homepage:
        href: http://truenas-scale:3000/
        description: My Homepage
        icon: homepage.png
    - Immich:
        href: http://truenas-scale:2283/
        description: Immich
        icon: immich.png
    - Dockge:
        href: http://truenas-scale:5001/
        description: Dockge
        icon: dockge.png
