---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Homepage
theme: dark

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  
layout:
  Services:
    style: row
    columns: 4
