// Package containers implements a manager for docker containers
package containers

import (
	"context"
	"fmt"
	"log/slog"
	"omar-kada/autonas/internal/config"
	"omar-kada/autonas/internal/files"
	"omar-kada/autonas/internal/shell"
	"omar-kada/autonas/models"
	"os"
	"path/filepath"
	"strings"

	"github.com/elliotchance/orderedmap/v3"
	"github.com/moby/moby/client"
)

// NewManager creates an instance of Manager for docker containers
func NewManager() *Deployer {
	return &Deployer{
		writer:    files.NewWriter(),
		cmdRunner: shell.NewRunner(),
	}
}

// Deployer manages Docker Compose services.
type Deployer struct {
	writer    files.Writer
	cmdRunner shell.Runner
}

// RemoveServices stops and removes Docker Compose services.
func (d Deployer) RemoveServices(services []string, servicesDir string) error {
	slog.Debug("these services will be removed if running.", "services", services)
	for _, serviceName := range services {
		err := d.composeDown(filepath.Join(servicesDir, serviceName))
		if err != nil {
			slog.Error("Error running docker compose down for %s: %v", serviceName, err)
		}
	}

	// TODO : return aggregated error instead of nil
	return nil
}

// DeployServices generates .env files and runs Docker Compose for enabled services.
func (d Deployer) DeployServices(cfg config.Config, servicesDir string) error {
	enabledServices := cfg.GetEnabledServices()
	if len(enabledServices) == 0 {
		slog.Warn("No enabled_services specified in config. Skipping .env generation and compose up.")
		return nil
	}

	for _, service := range enabledServices {
		if err := d.generateEnvFile(cfg, servicesDir, service); err != nil {
			slog.Error("Error creating env file", "service", service, "error", err)
		}
		if err := d.composeUp(filepath.Join(servicesDir, service)); err != nil {
			slog.Error("Error running docker compose", "service", service, "error", err)
		}
	}
	// TODO : return aggregated error instead of nil
	return nil
}

func (d Deployer) composeUp(composePath string) error {
	args := []string{"compose", "--project-directory", composePath, "up", "-d"}
	if err := d.cmdRunner.Run("docker", args...); err != nil {
		return fmt.Errorf("failed to run docker compose up : %w", err)
	}
	return nil
}

func (d Deployer) composeDown(composePath string) error {
	args := []string{"compose", "--project-directory", composePath, "down"}
	if err := d.cmdRunner.Run("docker", args...); err != nil {
		return fmt.Errorf("failed to run docker compose down : %w", err)
	}
	return nil
}

func (d Deployer) generateEnvFile(cfg config.Config, servicesDir, service string) error {
	serviceCfg := cfg.PerService(service)
	envFilePath := filepath.Join(servicesDir, service, ".env")

	envMap, err := parseEnvFile(envFilePath)
	if err != nil {
		return err
	}

	var content strings.Builder
	if envMap != nil {
		for key, rawLine := range envMap.AllFromFront() {
			if serviceCfg.Has(key) {
				content.WriteString(fmt.Sprintf("# %s # Overridden by AutoNAS \n", rawLine))
			} else {
				content.WriteString(fmt.Sprintf("%s\n", rawLine))
			}
		}
	}

	content.WriteString("# The next values are generated by AutoNAS : \n")

	for key, value := range serviceCfg.AllFromFront() {
		content.WriteString(fmt.Sprintf("%s=%v\n", key, value))
	}

	return d.writer.WriteToFile(envFilePath, content.String())
}

func parseEnvFile(path string) (*orderedmap.OrderedMap[string, string], error) {
	_, err := os.Stat(path)
	if err != nil {
		return nil, nil // file doesn't exists
	}
	fileContent, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	content := string(fileContent)
	lines := strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n")

	envMap := orderedmap.NewOrderedMap[string, string]()
	for index, rawLine := range lines {
		line := strings.TrimSpace(rawLine)
		splitLine := strings.Split(line, "=")
		if len(splitLine) > 1 {
			envMap.Set(strings.ToUpper(splitLine[0]), rawLine)
		} else {
			envMap.Set(fmt.Sprint(index), rawLine)
		}
	}
	return envMap, nil
}

// GetManagedContainers returns the list of containers (as returned by ContainerList)
// that are managed by AutoNAS
func (Deployer) GetManagedContainers(servicesDir string) (map[string][]models.ContainerSummary, error) {
	ctx := context.Background()
	cli, err := client.New(client.FromEnv, client.WithAPIVersionNegotiation())
	if err != nil {
		return nil, fmt.Errorf("failed to create docker client: %w", err)
	}
	defer cli.Close()

	summaries, err := cli.ContainerList(ctx, client.ContainerListOptions{All: true})
	if err != nil {
		return nil, fmt.Errorf("failed to list containers: %w", err)
	}

	matches := make(map[string][]models.ContainerSummary)
	for _, c := range summaries.Items {

		inspect, err := cli.ContainerInspect(ctx, c.ID, client.ContainerInspectOptions{})
		if err != nil {
			// don't fail entirely on single-container inspect error; just log and continue
			slog.Error("Failed to inspect container",
				"containerId", c.ID,
				"names", c.Names,
				"error", err)
			continue
		}

		for key, value := range inspect.Container.Config.Labels {
			slog.Debug(" found label ", "label", key, "value", value, "serviceDir", servicesDir)
			if strings.EqualFold(key, "com.docker.compose.project.working_dir") {
				after, found := strings.CutPrefix(value, servicesDir)
				if found {
					serviceName, _ := strings.CutPrefix(after, "/")
					slog.Debug("found prefix", "after", after, "serviceName", serviceName)
					matches[serviceName] = append(matches[serviceName], models.ContainerSummary{
						ID:     c.ID,
						Names:  c.Names,
						Image:  c.Image,
						State:  string(c.State),
						Status: c.Status,
					})
					break
				}
			}
		}
	}
	return matches, nil
}
