services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    labels:
      com.autonas.managed: true
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${PORT:-3000}:3000
    env_file:
      - .env
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ${DATA_PATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID # read them from .env
      PGID: $PGID # read them from .env
      HOMEPAGE_ALLOWED_HOSTS: ${HOST:-"host.docker.internal,localhost"}:${PORT:-3000} # replace $HOST with your actual hostname or IP
networks: {}
