// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package modelsdb

import (
	"errors"
	"log/slog"

	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type deployment_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var DeploymentBinding = deployment_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 4932359351954650694,
}

// Deployment_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Deployment_ = struct {
	Author  *objectbox.PropertyString
	Diff    *objectbox.PropertyString
	ID      *objectbox.PropertyUint64
	Status  *objectbox.PropertyString
	Time    *objectbox.PropertyInt64
	Title   *objectbox.PropertyString
	EndTime *objectbox.PropertyInt64
	Events  *objectbox.RelationToMany
	Files   *objectbox.RelationToMany
}{
	Author: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &DeploymentBinding.Entity,
		},
	},
	Diff: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &DeploymentBinding.Entity,
		},
	},
	ID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &DeploymentBinding.Entity,
		},
	},
	Status: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &DeploymentBinding.Entity,
		},
	},
	Time: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &DeploymentBinding.Entity,
		},
	},
	Title: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &DeploymentBinding.Entity,
		},
	},
	EndTime: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &DeploymentBinding.Entity,
		},
	},
	Events: &objectbox.RelationToMany{
		Id:     1,
		Source: &DeploymentBinding.Entity,
		Target: &EventBinding.Entity,
	},
	Files: &objectbox.RelationToMany{
		Id:     2,
		Source: &DeploymentBinding.Entity,
		Target: &FileDiffBinding.Entity,
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (deployment_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (deployment_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Deployment", 1, 4932359351954650694)
	model.Property("Author", 9, 1, 5594018983451234858)
	model.Property("Diff", 9, 2, 4163943653800901751)
	model.Property("ID", 6, 3, 357454033273744038)
	model.PropertyFlags(1)
	model.Property("Status", 9, 4, 8989814894901159613)
	model.Property("Time", 10, 5, 1269864842788429858)
	model.Property("Title", 9, 6, 7445546539675098816)
	model.Property("EndTime", 10, 7, 1672820934742845997)
	model.EntityLastPropertyId(7, 1672820934742845997)
	model.Relation(1, 5383246662726590361, EventBinding.Id, EventBinding.Uid)
	model.Relation(2, 6789058631577933099, FileDiffBinding.Id, FileDiffBinding.Uid)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (deployment_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Deployment).ID, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (deployment_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Deployment).ID = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (deployment_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	if err := BoxForDeployment(ob).RelationReplace(Deployment_.Events, id, object, object.(*Deployment).Events); err != nil {
		return err
	}

	if err := BoxForDeployment(ob).RelationReplace(Deployment_.Files, id, object, object.(*Deployment).Files); err != nil {
		return err
	}

	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (deployment_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Deployment)
	var propTime int64
	{
		var err error
		propTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.Time)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Deployment.Time: " + err.Error())
		}
	}

	var propEndTime int64
	{
		var err error
		propEndTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.EndTime)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Deployment.EndTime: " + err.Error())
		}
	}

	offsetAuthor := fbutils.CreateStringOffset(fbb, obj.Author)
	offsetDiff := fbutils.CreateStringOffset(fbb, obj.Diff)
	offsetStatus := fbutils.CreateStringOffset(fbb, string(obj.Status))
	offsetTitle := fbutils.CreateStringOffset(fbb, obj.Title)

	// build the FlatBuffers object
	fbb.StartObject(7)
	fbutils.SetUOffsetTSlot(fbb, 0, offsetAuthor)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetDiff)
	fbutils.SetUint64Slot(fbb, 2, id)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetStatus)
	fbutils.SetInt64Slot(fbb, 4, propTime)
	fbutils.SetInt64Slot(fbb, 6, propEndTime)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetTitle)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (deployment_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Deployment' - no data received")
	}

	table := &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	propID := table.GetUint64Slot(8, 0)

	propTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 12))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Deployment.Time: " + err.Error())
	}

	propEndTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 16))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Deployment.EndTime: " + err.Error())
	}

	var relEvents []*Event
	if rIds, err := BoxForDeployment(ob).RelationIds(Deployment_.Events, propID); err != nil {
		return nil, err
	} else if rSlice, err := BoxForEvent(ob).GetManyExisting(rIds...); err != nil {
		return nil, err
	} else {
		relEvents = rSlice
	}

	var relFiles []*FileDiff
	if rIds, err := BoxForDeployment(ob).RelationIds(Deployment_.Files, propID); err != nil {
		return nil, err
	} else if rSlice, err := BoxForFileDiff(ob).GetManyExisting(rIds...); err != nil {
		return nil, err
	} else {
		relFiles = rSlice
	}

	return &Deployment{
		Author:  fbutils.GetStringSlot(table, 4),
		Diff:    fbutils.GetStringSlot(table, 6),
		Events:  relEvents,
		Files:   relFiles,
		ID:      propID,
		Status:  DeploymentStatus(fbutils.GetStringSlot(table, 10)),
		Time:    propTime,
		EndTime: propEndTime,
		Title:   fbutils.GetStringSlot(table, 14),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (deployment_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Deployment, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (deployment_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Deployment), nil)
	}
	return append(slice.([]*Deployment), object.(*Deployment))
}

// Box provides CRUD access to Deployment objects
type DeploymentBox struct {
	*objectbox.Box
}

// BoxForDeployment opens a box of Deployment objects
func BoxForDeployment(ob *objectbox.ObjectBox) *DeploymentBox {
	return &DeploymentBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Deployment.ID property on the passed object will be assigned the new ID as well.
func (box *DeploymentBox) Put(object *Deployment) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Deployment.ID property on the passed object will be assigned the new ID as well.
func (box *DeploymentBox) Insert(object *Deployment) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *DeploymentBox) Update(object *Deployment) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *DeploymentBox) PutAsync(object *Deployment) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case IDs are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Deployment.ID property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Deployment.ID assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *DeploymentBox) PutMany(objects []*Deployment) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *DeploymentBox) Get(id uint64) (*Deployment, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Deployment), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *DeploymentBox) GetMany(ids ...uint64) ([]*Deployment, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Deployment), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *DeploymentBox) GetManyExisting(ids ...uint64) ([]*Deployment, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Deployment), nil
}

// GetAll reads all stored objects
func (box *DeploymentBox) GetAll() ([]*Deployment, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Deployment), nil
}

// Remove deletes a single object
func (box *DeploymentBox) Remove(object *Deployment) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *DeploymentBox) RemoveMany(objects ...*Deployment) (uint64, error) {
	ids := make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.ID
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Deployment_ struct to create conditions.
// Keep the *DeploymentQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *DeploymentBox) Query(conditions ...objectbox.Condition) *DeploymentQuery {
	return &DeploymentQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Deployment_ struct to create conditions.
// Keep the *DeploymentQuery if you intend to execute the query multiple times.
func (box *DeploymentBox) QueryOrError(conditions ...objectbox.Condition) (*DeploymentQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &DeploymentQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See DeploymentAsyncBox for more information.
func (box *DeploymentBox) Async() *DeploymentAsyncBox {
	return &DeploymentAsyncBox{AsyncBox: box.Box.Async()}
}

// DeploymentAsyncBox provides asynchronous operations on Deployment objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type DeploymentAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForDeployment creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use DeploymentBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForDeployment(ob *objectbox.ObjectBox, timeoutMs uint64) *DeploymentAsyncBox {
	async, err := objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &DeploymentAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the ID property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *DeploymentAsyncBox) Put(object *Deployment) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The ID property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *DeploymentAsyncBox) Insert(object *Deployment) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *DeploymentAsyncBox) Update(object *Deployment) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *DeploymentAsyncBox) Remove(object *Deployment) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Deployment which ID is either 42 or 47:
//
// box.Query(Deployment_.ID.In(42, 47)).Find()
type DeploymentQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *DeploymentQuery) Find() ([]*Deployment, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Deployment), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *DeploymentQuery) Offset(offset uint64) *DeploymentQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *DeploymentQuery) Limit(limit uint64) *DeploymentQuery {
	query.Query.Limit(limit)
	return query
}

type fileDiff_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var FileDiffBinding = fileDiff_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 5039716903289663534,
}

// FileDiff_ contains type-based Property helpers to facilitate some common operations such as Queries.
var FileDiff_ = struct {
	ID      *objectbox.PropertyUint64
	Diff    *objectbox.PropertyString
	NewFile *objectbox.PropertyString
	OldFile *objectbox.PropertyString
}{
	ID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &FileDiffBinding.Entity,
		},
	},
	Diff: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &FileDiffBinding.Entity,
		},
	},
	NewFile: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &FileDiffBinding.Entity,
		},
	},
	OldFile: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &FileDiffBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (fileDiff_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (fileDiff_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("FileDiff", 2, 5039716903289663534)
	model.Property("ID", 6, 1, 4865574112667400612)
	model.PropertyFlags(1)
	model.Property("Diff", 9, 2, 3375528542688359874)
	model.Property("NewFile", 9, 3, 4870050122345638650)
	model.Property("OldFile", 9, 4, 4196299902542153538)
	model.EntityLastPropertyId(4, 4196299902542153538)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (fileDiff_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*FileDiff).ID, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (fileDiff_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*FileDiff).ID = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (fileDiff_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (fileDiff_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*FileDiff)
	offsetDiff := fbutils.CreateStringOffset(fbb, obj.Diff)
	offsetNewFile := fbutils.CreateStringOffset(fbb, obj.NewFile)
	offsetOldFile := fbutils.CreateStringOffset(fbb, obj.OldFile)

	// build the FlatBuffers object
	fbb.StartObject(4)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetDiff)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetNewFile)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetOldFile)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (fileDiff_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'FileDiff' - no data received")
	}

	table := &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	propID := table.GetUint64Slot(4, 0)

	return &FileDiff{
		ID:      propID,
		Diff:    fbutils.GetStringSlot(table, 6),
		NewFile: fbutils.GetStringSlot(table, 8),
		OldFile: fbutils.GetStringSlot(table, 10),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (fileDiff_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*FileDiff, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (fileDiff_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*FileDiff), nil)
	}
	return append(slice.([]*FileDiff), object.(*FileDiff))
}

// Box provides CRUD access to FileDiff objects
type FileDiffBox struct {
	*objectbox.Box
}

// BoxForFileDiff opens a box of FileDiff objects
func BoxForFileDiff(ob *objectbox.ObjectBox) *FileDiffBox {
	return &FileDiffBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the FileDiff.ID property on the passed object will be assigned the new ID as well.
func (box *FileDiffBox) Put(object *FileDiff) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the FileDiff.ID property on the passed object will be assigned the new ID as well.
func (box *FileDiffBox) Insert(object *FileDiff) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *FileDiffBox) Update(object *FileDiff) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *FileDiffBox) PutAsync(object *FileDiff) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case IDs are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the FileDiff.ID property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the FileDiff.ID assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *FileDiffBox) PutMany(objects []*FileDiff) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *FileDiffBox) Get(id uint64) (*FileDiff, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*FileDiff), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *FileDiffBox) GetMany(ids ...uint64) ([]*FileDiff, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*FileDiff), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *FileDiffBox) GetManyExisting(ids ...uint64) ([]*FileDiff, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*FileDiff), nil
}

// GetAll reads all stored objects
func (box *FileDiffBox) GetAll() ([]*FileDiff, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*FileDiff), nil
}

// Remove deletes a single object
func (box *FileDiffBox) Remove(object *FileDiff) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *FileDiffBox) RemoveMany(objects ...*FileDiff) (uint64, error) {
	ids := make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.ID
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the FileDiff_ struct to create conditions.
// Keep the *FileDiffQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *FileDiffBox) Query(conditions ...objectbox.Condition) *FileDiffQuery {
	return &FileDiffQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the FileDiff_ struct to create conditions.
// Keep the *FileDiffQuery if you intend to execute the query multiple times.
func (box *FileDiffBox) QueryOrError(conditions ...objectbox.Condition) (*FileDiffQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &FileDiffQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See FileDiffAsyncBox for more information.
func (box *FileDiffBox) Async() *FileDiffAsyncBox {
	return &FileDiffAsyncBox{AsyncBox: box.Box.Async()}
}

// FileDiffAsyncBox provides asynchronous operations on FileDiff objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type FileDiffAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForFileDiff creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use FileDiffBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForFileDiff(ob *objectbox.ObjectBox, timeoutMs uint64) *FileDiffAsyncBox {
	async, err := objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &FileDiffAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the ID property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *FileDiffAsyncBox) Put(object *FileDiff) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The ID property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *FileDiffAsyncBox) Insert(object *FileDiff) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *FileDiffAsyncBox) Update(object *FileDiff) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *FileDiffAsyncBox) Remove(object *FileDiff) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all FileDiff which ID is either 42 or 47:
//
// box.Query(FileDiff_.ID.In(42, 47)).Find()
type FileDiffQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *FileDiffQuery) Find() ([]*FileDiff, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*FileDiff), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *FileDiffQuery) Offset(offset uint64) *FileDiffQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *FileDiffQuery) Limit(limit uint64) *FileDiffQuery {
	query.Query.Limit(limit)
	return query
}

type event_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var EventBinding = event_EntityInfo{
	Entity: objectbox.Entity{
		Id: 3,
	},
	Uid: 5824277623053869508,
}

// Event_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Event_ = struct {
	ID       *objectbox.PropertyUint64
	Level    *objectbox.PropertyInt
	Msg      *objectbox.PropertyString
	Time     *objectbox.PropertyInt64
	ObjectID *objectbox.PropertyUint64
}{
	ID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &EventBinding.Entity,
		},
	},
	Level: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &EventBinding.Entity,
		},
	},
	Msg: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &EventBinding.Entity,
		},
	},
	Time: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &EventBinding.Entity,
		},
	},
	ObjectID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &EventBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (event_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (event_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Event", 3, 5824277623053869508)
	model.Property("ID", 6, 1, 224148306401554185)
	model.PropertyFlags(1)
	model.Property("Level", 6, 2, 178468701704354373)
	model.Property("Msg", 9, 3, 4477093517829547794)
	model.Property("Time", 10, 4, 1874625364354129834)
	model.Property("ObjectID", 6, 5, 3273005205906032723)
	model.PropertyFlags(8192)
	model.EntityLastPropertyId(5, 3273005205906032723)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (event_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Event).ID, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (event_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Event).ID = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (event_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (event_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Event)
	var propTime int64
	{
		var err error
		propTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.Time)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Event.Time: " + err.Error())
		}
	}

	offsetMsg := fbutils.CreateStringOffset(fbb, obj.Msg)

	// build the FlatBuffers object
	fbb.StartObject(5)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetInt64Slot(fbb, 1, int64(int(obj.Level)))
	fbutils.SetUOffsetTSlot(fbb, 2, offsetMsg)
	fbutils.SetInt64Slot(fbb, 3, propTime)
	fbutils.SetUint64Slot(fbb, 4, obj.ObjectID)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (event_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Event' - no data received")
	}

	table := &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	propID := table.GetUint64Slot(4, 0)

	propTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 10))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Event.Time: " + err.Error())
	}

	return &Event{
		ID:       propID,
		Level:    slog.Level(fbutils.GetIntSlot(table, 6)),
		Msg:      fbutils.GetStringSlot(table, 8),
		Time:     propTime,
		ObjectID: fbutils.GetUint64Slot(table, 12),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (event_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Event, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (event_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Event), nil)
	}
	return append(slice.([]*Event), object.(*Event))
}

// Box provides CRUD access to Event objects
type EventBox struct {
	*objectbox.Box
}

// BoxForEvent opens a box of Event objects
func BoxForEvent(ob *objectbox.ObjectBox) *EventBox {
	return &EventBox{
		Box: ob.InternalBox(3),
	}
}

// Put synchronously inserts/updates a single object.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Event.ID property on the passed object will be assigned the new ID as well.
func (box *EventBox) Put(object *Event) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Event.ID property on the passed object will be assigned the new ID as well.
func (box *EventBox) Insert(object *Event) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *EventBox) Update(object *Event) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *EventBox) PutAsync(object *Event) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case IDs are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Event.ID property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Event.ID assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *EventBox) PutMany(objects []*Event) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *EventBox) Get(id uint64) (*Event, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Event), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *EventBox) GetMany(ids ...uint64) ([]*Event, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Event), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *EventBox) GetManyExisting(ids ...uint64) ([]*Event, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Event), nil
}

// GetAll reads all stored objects
func (box *EventBox) GetAll() ([]*Event, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Event), nil
}

// Remove deletes a single object
func (box *EventBox) Remove(object *Event) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *EventBox) RemoveMany(objects ...*Event) (uint64, error) {
	ids := make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.ID
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Event_ struct to create conditions.
// Keep the *EventQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *EventBox) Query(conditions ...objectbox.Condition) *EventQuery {
	return &EventQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Event_ struct to create conditions.
// Keep the *EventQuery if you intend to execute the query multiple times.
func (box *EventBox) QueryOrError(conditions ...objectbox.Condition) (*EventQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &EventQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See EventAsyncBox for more information.
func (box *EventBox) Async() *EventAsyncBox {
	return &EventAsyncBox{AsyncBox: box.Box.Async()}
}

// EventAsyncBox provides asynchronous operations on Event objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type EventAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForEvent creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use EventBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForEvent(ob *objectbox.ObjectBox, timeoutMs uint64) *EventAsyncBox {
	async, err := objectbox.NewAsyncBox(ob, 3, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 3: %s" + err.Error())
	}
	return &EventAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the ID property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *EventAsyncBox) Put(object *Event) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The ID property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *EventAsyncBox) Insert(object *Event) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *EventAsyncBox) Update(object *Event) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *EventAsyncBox) Remove(object *Event) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Event which ID is either 42 or 47:
//
// box.Query(Event_.ID.In(42, 47)).Find()
type EventQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *EventQuery) Find() ([]*Event, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Event), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *EventQuery) Offset(offset uint64) *EventQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *EventQuery) Limit(limit uint64) *EventQuery {
	query.Query.Limit(limit)
	return query
}
