// Code generated by ObjectBox; DO NOT EDIT.

package modelsdb

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(DeploymentBinding)
	model.RegisterBinding(FileDiffBinding)
	model.RegisterBinding(EventBinding)
	model.LastEntityId(3, 5824277623053869508)

	model.LastRelationId(2, 6789058631577933099)

	return model
}
